config {
  type: "table",
    bigquery: {
    partitionBy: "report_date"
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "all_apps_id1010631459_platforms_merged_metrics_all_cost_geo_unique_with_links",
  schema: "id1010631459_appsflyer_ds",
  dependencies: ['id1010631459_platforms_merged_metrics_all_cost_geo_unique_with_links'],
  tags: ['appsflyer_id1010631459_main']
}


WITH
  country_names AS (
  SELECT
    *
  FROM
    `rockads-thirdparty.mapping_tables.countries`
  WHERE
    short_code != 'GB' ),
  subscription_sales AS (
  SELECT
    *
  FROM
    `rockads-thirdparty.company_stats.company_subscription_sales`
  WHERE
    company = 'Getcontact'
    AND platform != 'Web' ),
  superset_revenues AS (
  SELECT
    ss.*,
    c.short_code AS geo
  FROM
    subscription_sales ss
  LEFT JOIN
    country_names c
  ON
    ss.country_name = c.name )


SELECT non_rltv.*,
rltv.d1 as d1,
rltv.d3 as d3,
rltv.d7 as d7,
rltv.d15 as d15,
rltv.d30 as d30,
rltv.d60 AS d60,
rltv.d90 AS d90,
rltv.d120 AS d120,
rltv.d150 AS d150,
rltv.d180 AS d180,
rltv.d210 AS d210,
rltv.d240 AS d240,
rltv.d270 AS d270,
rltv.d360 AS d360,
rltv.ltv as ltv,

zotlo_rltv.d0 as zotlo_d0,
zotlo_rltv.d1 as zotlo_d1,
zotlo_rltv.d3 as zotlo_d3,
zotlo_rltv.d7 as zotlo_d7,
zotlo_rltv.d15 as zotlo_d15,
zotlo_rltv.d30 as zotlo_d30,
zotlo_rltv.d60   AS zotlo_d60,
zotlo_rltv.d90   AS zotlo_d90,
zotlo_rltv.d120  AS zotlo_d120,
zotlo_rltv.d150  AS zotlo_d150,
zotlo_rltv.d180  AS zotlo_d180,
zotlo_rltv.d210  AS zotlo_d210,
zotlo_rltv.d240  AS zotlo_d240,
zotlo_rltv.d270  AS zotlo_d270,
zotlo_rltv.d360  AS zotlo_d360,
zotlo_rltv.ltv as zotlo_ltv,

FROM (

SELECT
    IFNULL(ltv.report_date, activity.report_date) AS report_date,
    'id1010631459' as app_id,
    IFNULL(ltv.geo, activity.geo) as geo,
    IFNULL(ltv.campaign, activity.campaign) as campaign,
    IFNULL(ltv.adset, activity.af_adset) as adset,
    IFNULL(ltv.ad, activity.ad) as ad,
    IFNULL(ltv.media_source, activity.media_source) as media_source,
    IFNULL(ltv.appsflyer_os_id, activity.appsflyer_os_id) as appsflyer_os_id,
    vnew,
    vreturning,
    cc_success_total,
    subscribe,
    start_trial,
    recurring_payment,
    unique_vnew,
    unique_vreturning,
    unique_cc_success_total,
    unique_subscribe,
    unique_start_trial,
    unique_recurring_payment,
    event_revenue,
    total_cost,
    total_clicks,
    total_installs,
    total_impressions,
    total_re_attributions,
    total_re_engagements,
    total_video_completions,
    total_video_25p_views,
    total_video_50p_views,
    total_video_75p_views,
    fb_total_outbound_clicks,
    fb_total_impressions,
    fb_total_clicks,
    thumbnail_url,
    video_url,
    total_master_installs,

    -- Activity Report
    activity.activity_vnew,
    activity.activity_vreturning,
    activity.activity_cc_success_total,
    activity.activity_subscribe,
    activity.activity_start_trial,
    activity.activity_recurring_payment,
    -- Unique event counts
    activity.activity_unique_vnew,
    activity.activity_unique_vreturning,
    activity.activity_unique_cc_success_total,
    activity.activity_unique_subscribe,
    activity.activity_unique_start_trial,
    activity.activity_unique_recurring_payment,
    activity.activity_event_revenue,

    NULL as zotlo_activity_event_revenue,
    NULL AS zotlo_activity_event_count_reactive,
    NULL AS zotlo_activity_revenue_reactive,
    NULL AS zotlo_activity_event_count_trial_to_paid,
    NULL AS zotlo_activity_revenue_trial_to_paid,
    NULL AS zotlo_activity_event_count_trial,
    NULL AS zotlo_activity_revenue_trial,
    NULL AS zotlo_activity_event_count_renewal,
    NULL AS zotlo_activity_revenue_renewal,
    NULL AS zotlo_activity_event_count_set_quantity,
    NULL AS zotlo_activity_revenue_set_quantity,
    NULL AS zotlo_activity_event_count_consumable,
    NULL AS zotlo_activity_revenue_consumable,
    NULL AS zotlo_activity_event_count_start_paid,
    NULL AS zotlo_activity_revenue_start_paid,
    NULL AS zotlo_activity_event_count_package_upgrate,
    NULL AS zotlo_activity_revenue_package_upgrate,
    NULL AS zotlo_activity_event_count_epin,
    NULL AS zotlo_activity_revenue_epin,
    NULL AS zotlo_activity_event_count_package_upgrade,
    NULL AS zotlo_activity_revenue_package_upgrade,

    NULL  as zotlo_overview_event_revenue,
    NULL AS zotlo_overview_event_count_reactive,
    NULL AS zotlo_overview_revenue_reactive,
    NULL AS zotlo_overview_event_count_trial_to_paid,
    NULL AS zotlo_overview_revenue_trial_to_paid,
    NULL AS zotlo_overview_event_count_trial,
    NULL AS zotlo_overview_revenue_trial,
    NULL AS zotlo_overview_event_count_renewal,
    NULL AS zotlo_overview_revenue_renewal,
    NULL AS zotlo_overview_event_count_set_quantity,
    NULL AS zotlo_overview_revenue_set_quantity,
    NULL AS zotlo_overview_event_count_consumable,
    NULL AS zotlo_overview_revenue_consumable,
    NULL AS zotlo_overview_event_count_start_paid,
    NULL AS zotlo_overview_revenue_start_paid,
    NULL AS zotlo_overview_event_count_package_upgrate,
    NULL AS zotlo_overview_revenue_package_upgrate,
    NULL AS zotlo_overview_event_count_epin,
    NULL AS zotlo_overview_revenue_epin,
    NULL AS zotlo_overview_event_count_package_upgrade,
    NULL AS zotlo_overview_revenue_package_upgrade,

    CAST(NULL AS FLOAT64) AS activity_total_proceeds,
    CAST(NULL AS FLOAT64) AS activity_total_sales_count,
    CAST(NULL AS FLOAT64) AS activity_total_refund_count

FROM (

SELECT
    IFNULL(main.report_date, master.install_time) AS report_date,
    'id1010631459' as app_id,
    IFNULL(main.geo, master.geo) as geo,
    IFNULL(main.campaign, master.campaign) as campaign,
    IFNULL(main.adset, master.adset) as adset,
    IFNULL(main.ad, master.ad) as ad,
    IFNULL(main.media_source, master.media_source) as media_source,
    IFNULL(main.appsflyer_os_id, master.appsflyer_app_id) as appsflyer_os_id,
    main.vnew,
    main.vreturning,
    main.cc_success_total,
    main.subscribe,
    main.start_trial,
    main.recurring_payment,
    main.unique_vnew,
    main.unique_vreturning,
    main.unique_cc_success_total,
    main.unique_subscribe,
    main.unique_start_trial,
    main.unique_recurring_payment,
    main.event_revenue,
    main.total_cost,
    main.total_clicks,
    main.total_installs,
    main.total_impressions,
    main.total_re_attributions,
    main.total_re_engagements,
    main.total_video_completions,
    main.total_video_25p_views,
    main.total_video_50p_views,
    main.total_video_75p_views,
    main.fb_total_outbound_clicks,
    main.fb_total_impressions,
    main.fb_total_clicks,
    main.thumbnail_url,
    main.video_url,
    master.total_master_installs

FROM (
SELECT
  main.*,
  IFNULL(links.thumbnail_url, tiktok_links.thumbnail_url) AS thumbnail_url,
  IFNULL(links.video_url, tiktok_links.video_url) AS video_url
FROM
  `rockads-thirdparty.id1010631459_appsflyer_ds.id1010631459_platforms_merged_metrics_all_cost_geo_unique` main
LEFT JOIN
  `rockads-thirdparty.id1010631459_appsflyer_ds.id1010631459_facebook_links_urls` links
ON
  main.app_id=links.app_id
  AND main.ad=links.ad
  AND IF(main.media_source = 'facebook', 'Facebook Ads', main.media_source) = links.media_source
LEFT JOIN
  `rockads-thirdparty.id1010631459_appsflyer_ds.id1010631459_tiktok_links_urls` tiktok_links
ON
  main.app_id=tiktok_links.app_id
  AND main.ad=tiktok_links.ad
  AND IF(main.media_source = 'tiktok', 'tiktokglobal_int', main.media_source) = tiktok_links.media_source

UNION ALL
SELECT
  report_date,
  app_id,
  geo,
  campaign,
  adset,
  ad,
  media_source,
  appsflyer_os_id,
  vnew,
  vreturning,
  cc_success_total,
  subscribe,
  start_trial,
  recurring_payment,
  unique_vnew,
  unique_vreturning,
  unique_cc_success_total,
  unique_subscribe,
  unique_start_trial,
  unique_recurring_payment,
  event_revenue,
  total_cost,
  total_clicks,
  total_installs,
  total_impressions,
  total_re_attributions,
  total_re_engagements,
  total_video_completions,
  total_video_25p_views,
  total_video_50p_views,
  total_video_75p_views,
  fb_total_outbound_clicks,
  fb_total_impressions,
  fb_total_clicks,
  thumbnail_url,
  video_url
FROM
  `rockads-thirdparty.id1010631459_appsflyer_ds.id1010631459_organic_combined_metrics_unique_dm`
) main

# Master Metrics Part (join)
FULL OUTER JOIN (
  SELECT
    install_time,
    REPLACE(appsflyer_app_id, '.', '_') appsflyer_app_id,
    campaign,
    adset,
    ad,
    geo,
    media_source,
    SUM(installs) AS total_master_installs
  FROM
    `rockads-thirdparty.all_appsflyer_ds.all_apps_master_metrics`
  WHERE
    install_time >= "2025-01-01"
    AND appsflyer_app_id IN ('id1010631459',
      'app.source.getcontact')
    AND geo != 'None'
    AND installs > 0
  GROUP BY
    1,
    2,
    3,
    4,
    5,
    6,
    7) master
ON
  main.report_date=master.install_time
  AND main.appsflyer_os_id=master.appsflyer_app_id
  AND main.campaign=master.campaign
  AND main.adset=master.adset
  AND main.ad=master.ad
  AND main.geo=master.geo
  AND main.media_source=master.media_source



) ltv
# Activity Part

FULL OUTER JOIN rockads-thirdparty.id1010631459_appsflyer_ds.id1010631459_activity_union AS activity
ON
  ltv.report_date=activity.report_date
  AND ltv.app_id=activity.app_id
  AND ltv.geo=activity.geo
  AND ltv.campaign=activity.campaign
  AND ltv.adset=activity.af_adset
  AND ltv.ad=activity.ad
  AND ltv.media_source=activity.media_source
  AND ltv.appsflyer_os_id=activity.appsflyer_os_id


UNION ALL
SELECT
    z.report_date,
    'id1010631459' as app_id,
    z.country_code AS geo,
    CONCAT('webpayment_', IFNULL(z.campaign_name, '')) AS campaign,
    IFNULL(z.ad_group_name, '') AS adset,
    IFNULL(z.ad_name, '')  AS ad,
    CONCAT('zotlo-', IF(z.media_source is NULL,'',z.media_source)) AS media_source,
    NULL AS appsflyer_os_id,
    NULL AS vnew,
    NULL AS vreturning,
    NULL AS cc_success_total,
    NULL AS subscribe,
    NULL AS start_trial,
    NULL AS recurring_payment,
    NULL AS unique_vnew,
    NULL AS unique_vreturning,
    NULL AS unique_cc_success_total,
    NULL AS unique_subscribe,
    NULL AS unique_start_trial,
    NULL AS unique_recurring_payment,
    NULL AS event_revenue,
    NULL AS total_cost,
    NULL AS total_clicks,
    NULL AS total_installs,
    NULL AS total_impressions,
    NULL AS total_re_attributions,
    NULL AS total_re_engagements,
    NULL AS total_video_completions,
    NULL AS total_video_25p_views,
    NULL AS total_video_50p_views,
    NULL AS total_video_75p_views,
    NULL AS fb_total_outbound_clicks,
    NULL AS fb_total_impressions,
    NULL AS fb_total_clicks,
    NULL AS thumbnail_url,
    NULL AS video_url,
    NULL AS total_master_installs,
    NULL AS activity_vnew,
    NULL AS activity_vreturning,
    NULL AS activity_cc_success_total,
    NULL AS activity_subscribe,
    NULL AS activity_start_trial,
    NULL AS activity_recurring_payment,
    NULL AS activity_unique_vnew,
    NULL AS activity_unique_vreturning,
    NULL AS activity_unique_cc_success_total,
    NULL AS activity_unique_subscribe,
    NULL AS activity_unique_start_trial,
    NULL AS activity_unique_recurring_payment,
    NULL AS activity_event_revenue,

    SUM(z.zotlo_activity_event_revenue) as zotlo_activity_event_revenue,
    SUM(activity_event_count_reactive) zotlo_activity_event_count_reactive,
    SUM(activity_revenue_reactive) zotlo_activity_revenue_reactive,
    SUM(activity_event_count_trial_to_paid) zotlo_activity_event_count_trial_to_paid,
    SUM(activity_revenue_trial_to_paid) zotlo_activity_revenue_trial_to_paid,
    SUM(activity_event_count_trial) zotlo_activity_event_count_trial,
    SUM(activity_revenue_trial) zotlo_activity_revenue_trial,
    SUM(activity_event_count_renewal) zotlo_activity_event_count_renewal,
    SUM(activity_revenue_renewal) zotlo_activity_revenue_renewal,
    SUM(activity_event_count_set_quantity) zotlo_activity_event_count_set_quantity ,
    SUM(activity_revenue_set_quantity) zotlo_activity_revenue_set_quantity ,
    SUM(activity_event_count_consumable) zotlo_activity_event_count_consumable,
    SUM(activity_revenue_consumable) zotlo_activity_revenue_consumable,
    SUM(activity_event_count_start_paid) zotlo_activity_event_count_start_paid,
    SUM(activity_revenue_start_paid) zotlo_activity_revenue_start_paid,
    SUM(activity_event_count_package_upgrate) zotlo_activity_event_count_package_upgrate,
    SUM(activity_revenue_package_upgrate) zotlo_activity_revenue_package_upgrate,
    SUM(activity_event_count_epin) zotlo_activity_event_count_epin,
    SUM(activity_revenue_epin) zotlo_activity_revenue_epin,
    SUM(activity_event_count_package_upgrade) zotlo_activity_event_count_package_upgrade,
    SUM(activity_revenue_package_upgrade) zotlo_activity_revenue_package_upgrade,

    NULL  as zotlo_overview_event_revenue,
    NULL AS zotlo_overview_event_count_reactive,
    NULL AS zotlo_overview_revenue_reactive,
    NULL AS zotlo_overview_event_count_trial_to_paid,
    NULL AS zotlo_overview_revenue_trial_to_paid,
    NULL AS zotlo_overview_event_count_trial,
    NULL AS zotlo_overview_revenue_trial,
    NULL AS zotlo_overview_event_count_renewal,
    NULL AS zotlo_overview_revenue_renewal,
    NULL AS zotlo_overview_event_count_set_quantity,
    NULL AS zotlo_overview_revenue_set_quantity,
    NULL AS zotlo_overview_event_count_consumable,
    NULL AS zotlo_overview_revenue_consumable,
    NULL AS zotlo_overview_event_count_start_paid,
    NULL AS zotlo_overview_revenue_start_paid,
    NULL AS zotlo_overview_event_count_package_upgrate,
    NULL AS zotlo_overview_revenue_package_upgrate,
    NULL AS zotlo_overview_event_count_epin,
    NULL AS zotlo_overview_revenue_epin,
    NULL AS zotlo_overview_event_count_package_upgrade,
    NULL AS zotlo_overview_revenue_package_upgrade,

    CAST(NULL AS FLOAT64) AS activity_total_proceeds,
    CAST(NULL AS FLOAT64) AS activity_total_sales_count,
    CAST(NULL AS FLOAT64) AS activity_total_refund_count

FROM (
SELECT
report_date,
    'id1010631459' as app_id,
    IF(country_code='GB', 'UK', country_code) AS country_code,
    IFNULL(campaign_name, '') as campaign_name,
    IFNULL(ad_group_name, '') as ad_group_name,
    IFNULL(ad_name, '') ad_name,
    IFNULL(media_source, '') as media_source,
    SUM(amount) as zotlo_activity_event_revenue
FROM
  `rockads-thirdparty.zotlo_marketing_ds.ads_purchase_refund_combined_zotlo`
WHERE
  app_name IN
  ('Getcontact')
GROUP BY ALL
 ) z

LEFT JOIN (


WITH main_raw_data AS (SELECT  IFNULL(campaign_name, '') as campaign_name, IFNULL(ad_group_name, '') as ad_group_name, 'id1010631459' AS app_id,  IFNULL(ad_name, '') ad_name, IFNULL(media_source, '') as media_source, event_name,
IF(country_code='GB', 'UK', country_code) AS country_code,
amount,
event_count,
DATE(report_date) as event_date,
FROM rockads-thirdparty.zotlo_marketing_ds.ads_purchase_refund_combined_zotlo
WHERE app_name IN
  ('Getcontact')

)
SELECT * FROM (
SELECT campaign_name, ad_group_name, app_id,  ad_name, IF(country_code='GB', 'UK', country_code) AS country_code,
media_source, event_name,
event_date,
SUM(event_count) AS event_count,
sum(CAST(amount AS FLOAT64)) AS revenue,
FROM main_raw_data
GROUP BY ALL
)
PIVOT (
  MAX(event_count) as activity_event_count,
  MAX(revenue)  as activity_revenue FOR event_name IN (
    'reactive',
    'trial_to_paid',
    'trial',
    'renewal',
    'set_quantity',
    'consumable',
    'start_paid',
    'package_upgrate',
    'epin',
    'package_upgrade'
  )
)


)ec

ON
z.report_date = ec.event_date AND
z.country_code = ec.country_code AND
IFNULL(z.campaign_name,'') = IFNULL(ec.campaign_name,'')  AND
IFNULL(z.ad_group_name,'') = IFNULL(ec.ad_group_name,'')  AND
IFNULL(z.ad_name,'') = IFNULL(ec.ad_name,'') AND
CONCAT('zotlo-', IF(z.media_source is NULL,'',z.media_source)) = CONCAT('zotlo-', IF(ec.media_source is NULL,'',ec.media_source))
GROUP BY ALL

# Overview Zotlo

UNION ALL
SELECT
    z.report_date,
    'id1010631459' as app_id,
    z.country_code AS geo,
    IFNULL(z.campaign_name, '') AS campaign,
    IFNULL(z.ad_group_name, '') AS adset,
    IFNULL(z.ad_name, '')  AS ad,
    CONCAT('zotlo-', IF(z.media_source is NULL,'',z.media_source)) AS media_source,
    NULL AS appsflyer_os_id,
    NULL AS vnew,
    NULL AS vreturning,
    NULL AS cc_success_total,
    NULL AS subscribe,
    NULL AS start_trial,
    NULL AS recurring_payment,
    NULL AS unique_vnew,
    NULL AS unique_vreturning,
    NULL AS unique_cc_success_total,
    NULL AS unique_subscribe,
    NULL AS unique_start_trial,
    NULL AS unique_recurring_payment,
    NULL AS event_revenue,
    NULL AS total_cost,
    NULL AS total_clicks,
    NULL AS total_installs,
    NULL AS total_impressions,
    NULL AS total_re_attributions,
    NULL AS total_re_engagements,
    NULL AS total_video_completions,
    NULL AS total_video_25p_views,
    NULL AS total_video_50p_views,
    NULL AS total_video_75p_views,
    NULL AS fb_total_outbound_clicks,
    NULL AS fb_total_impressions,
    NULL AS fb_total_clicks,
    NULL AS thumbnail_url,
    NULL AS video_url,
    NULL AS total_master_installs,
    NULL AS activity_vnew,
    NULL AS activity_vreturning,
    NULL AS activity_cc_success_total,
    NULL AS activity_subscribe,
    NULL AS activity_start_trial,
    NULL AS activity_recurring_payment,
    NULL AS activity_unique_vnew,
    NULL AS activity_unique_vreturning,
    NULL AS activity_unique_cc_success_total,
    NULL AS activity_unique_subscribe,
    NULL AS activity_unique_start_trial,
    NULL AS activity_unique_recurring_payment,
    NULL AS activity_event_revenue,

    NULL  as zotlo_activity_event_revenue,
    NULL AS zotlo_activity_event_count_reactive,
    NULL AS zotlo_activity_revenue_reactive,
    NULL AS zotlo_activity_event_count_trial_to_paid,
    NULL AS zotlo_activity_revenue_trial_to_paid,
    NULL AS zotlo_activity_event_count_trial,
    NULL AS zotlo_activity_revenue_trial,
    NULL AS zotlo_activity_event_count_renewal,
    NULL AS zotlo_activity_revenue_renewal,
    NULL AS zotlo_activity_event_count_set_quantity,
    NULL AS zotlo_activity_revenue_set_quantity,
    NULL AS zotlo_activity_event_count_consumable,
    NULL AS zotlo_activity_revenue_consumable,
    NULL AS zotlo_activity_event_count_start_paid,
    NULL AS zotlo_activity_revenue_start_paid,
    NULL AS zotlo_activity_event_count_package_upgrate,
    NULL AS zotlo_activity_revenue_package_upgrate,
    NULL AS zotlo_activity_event_count_epin,
    NULL AS zotlo_activity_revenue_epin,
    NULL AS zotlo_activity_event_count_package_upgrade,
    NULL AS zotlo_activity_revenue_package_upgrade,

    SUM(z.zotlo_overview_event_revenue) as zotlo_overview_event_revenue,
    SUM(overview_event_count_reactive) zotlo_overview_event_count_reactive,
    SUM(overview_revenue_reactive) zotlo_overview_revenue_reactive,
    SUM(overview_event_count_trial_to_paid) zotlo_overview_event_count_trial_to_paid,
    SUM(overview_revenue_trial_to_paid) zotlo_overview_revenue_trial_to_paid,
    SUM(overview_event_count_trial) zotlo_overview_event_count_trial,
    SUM(overview_revenue_trial) zotlo_overview_revenue_trial,
    SUM(overview_event_count_renewal) zotlo_overview_event_count_renewal,
    SUM(overview_revenue_renewal) zotlo_overview_revenue_renewal,
    SUM(overview_event_count_set_quantity) zotlo_overview_event_count_set_quantity ,
    SUM(overview_revenue_set_quantity) zotlo_overview_revenue_set_quantity ,
    SUM(overview_event_count_consumable) zotlo_overview_event_count_consumable,
    SUM(overview_revenue_consumable) zotlo_overview_revenue_consumable,
    SUM(overview_event_count_start_paid) zotlo_overview_event_count_start_paid,
    SUM(overview_revenue_start_paid) zotlo_overview_revenue_start_paid,
    SUM(overview_event_count_package_upgrate) zotlo_overview_event_count_package_upgrate,
    SUM(overview_revenue_package_upgrate) zotlo_overview_revenue_package_upgrate,
    SUM(overview_event_count_epin) zotlo_overview_event_count_epin,
    SUM(overview_revenue_epin) zotlo_overview_revenue_epin,
    SUM(overview_event_count_package_upgrade) zotlo_overview_event_count_package_upgrade,
    SUM(overview_revenue_package_upgrade) zotlo_overview_revenue_package_upgrade,

    CAST(NULL AS FLOAT64) AS activity_total_proceeds,
    CAST(NULL AS FLOAT64) AS activity_total_sales_count,
    CAST(NULL AS FLOAT64) AS activity_total_refund_count

FROM (
SELECT
report_date,
    'id1010631459' as app_id,
    IF(country_code='GB', 'UK', country_code) AS country_code,
    IFNULL(campaign_name, '') as campaign_name,
    IFNULL(ad_group_name, '') as ad_group_name,
    IFNULL(ad_name, '') ad_name,
    IFNULL(media_source, '') as media_source,
    SUM(amount) as zotlo_overview_event_revenue,

FROM
  `rockads-thirdparty.zotlo_marketing_ds.overview_ads_purchase_refund_combined_zotlo`


WHERE
  app_name IN
  ('Getcontact')
GROUP BY ALL
) z
LEFT JOIN (


WITH main_raw_data AS (SELECT  IFNULL(campaign_name, '') as campaign_name, IFNULL(ad_group_name, '') as ad_group_name, 'id1010631459' AS app_id, IFNULL(ad_name, '') ad_name, IFNULL(media_source, '') as media_source, event_name,
IF(country_code='GB', 'UK', country_code) AS country_code,
amount,
event_count,
DATE(report_date) as event_date,
FROM rockads-thirdparty.zotlo_marketing_ds.overview_ads_purchase_refund_combined_zotlo
WHERE app_name IN
  ('Getcontact')

)
SELECT * FROM (
SELECT campaign_name, ad_group_name, app_id,  ad_name, IF(country_code='GB', 'UK', country_code) AS country_code,
media_source, event_name,
event_date,
SUM(event_count) AS event_count,
sum(CAST(amount AS FLOAT64)) AS revenue,
FROM main_raw_data
GROUP BY ALL
)
PIVOT (
  MAX(event_count) as overview_event_count,
  MAX(revenue)  as overview_revenue FOR event_name IN (
    'reactive',
    'trial_to_paid',
    'trial',
    'renewal',
    'set_quantity',
    'consumable',
    'start_paid',
    'package_upgrate',
    'epin',
    'package_upgrade'
  )
)


)ec

ON
z.report_date = ec.event_date AND
z.country_code = ec.country_code AND
IFNULL(z.campaign_name,'') = IFNULL(ec.campaign_name,'') AND
IFNULL(z.ad_group_name,'') = IFNULL(ec.ad_group_name,'')  AND
IFNULL(z.ad_name,'') = IFNULL(ec.ad_name,'') AND
CONCAT('zotlo-', IF(z.media_source is NULL,'',z.media_source)) = CONCAT('zotlo-', IF(ec.media_source is NULL,'',ec.media_source))
group by all

# Superset revenues
UNION ALL
SELECT
  date as report_date,
  'id1010631459' as app_id,
  geo,
  'Superset-Campaign' as campaign,
  'Superset-Adset' as adset,
  'Superset-Ad' as ad,
  'Superset-Media_Source' as media_source,
  IF(platform = 'iOS', 'id1010631459', IF(platform='Android', 'app_source_getcontact', NULL)) AS appsflyer_os_id,
  NULL AS vnew,
  NULL AS vreturning,
  NULL AS cc_success_total,
  NULL AS subscribe,
  NULL AS start_trial,
  NULL AS recurring_payment,
  NULL AS unique_vnew,
  NULL AS unique_vreturning,
  NULL AS unique_cc_success_total,
  NULL AS unique_subscribe,
  NULL AS unique_start_trial,
  NULL AS unique_recurring_payment,
  NULL AS event_revenue,
  NULL AS total_cost,
  NULL AS total_clicks,
  NULL AS total_installs,
  NULL AS total_impressions,
  NULL AS total_re_attributions,
  NULL AS total_re_engagements,
  NULL AS total_video_completions,
  NULL AS total_video_25p_views,
  NULL AS total_video_50p_views,
  NULL AS total_video_75p_views,
  NULL AS fb_total_outbound_clicks,
  NULL AS fb_total_impressions,
  NULL AS fb_total_clicks,
  NULL AS thumbnail_url,
  NULL AS video_url,
  NULL AS total_master_installs,
  NULL AS activity_vnew,
  NULL AS activity_vreturning,
  NULL AS activity_cc_success_total,
  NULL AS activity_subscribe,
  NULL AS activity_start_trial,
  NULL AS activity_recurring_payment,
  NULL AS activity_unique_vnew,
  NULL AS activity_unique_vreturning,
  NULL AS activity_unique_cc_success_total,
  NULL AS activity_unique_subscribe,
  NULL AS activity_unique_start_trial,
  NULL AS activity_unique_recurring_payment,
  NULL AS activity_event_revenue,

  NULL as zotlo_activity_event_revenue,
  NULL AS zotlo_activity_event_count_reactive,
  NULL AS zotlo_activity_revenue_reactive,
  NULL AS zotlo_activity_event_count_trial_to_paid,
  NULL AS zotlo_activity_revenue_trial_to_paid,
  NULL AS zotlo_activity_event_count_trial,
  NULL AS zotlo_activity_revenue_trial,
  NULL AS zotlo_activity_event_count_renewal,
  NULL AS zotlo_activity_revenue_renewal,
  NULL AS zotlo_activity_event_count_set_quantity,
  NULL AS zotlo_activity_revenue_set_quantity,
  NULL AS zotlo_activity_event_count_consumable,
  NULL AS zotlo_activity_revenue_consumable,
  NULL AS zotlo_activity_event_count_start_paid,
  NULL AS zotlo_activity_revenue_start_paid,
  NULL AS zotlo_activity_event_count_package_upgrate,
  NULL AS zotlo_activity_revenue_package_upgrate,
  NULL AS zotlo_activity_event_count_epin,
  NULL AS zotlo_activity_revenue_epin,
  NULL AS zotlo_activity_event_count_package_upgrade,
  NULL AS zotlo_activity_revenue_package_upgrade,

  NULL  as zotlo_overview_event_revenue,
  NULL AS zotlo_overview_event_count_reactive,
  NULL AS zotlo_overview_revenue_reactive,
  NULL AS zotlo_overview_event_count_trial_to_paid,
  NULL AS zotlo_overview_revenue_trial_to_paid,
  NULL AS zotlo_overview_event_count_trial,
  NULL AS zotlo_overview_revenue_trial,
  NULL AS zotlo_overview_event_count_renewal,
  NULL AS zotlo_overview_revenue_renewal,
  NULL AS zotlo_overview_event_count_set_quantity,
  NULL AS zotlo_overview_revenue_set_quantity,
  NULL AS zotlo_overview_event_count_consumable,
  NULL AS zotlo_overview_revenue_consumable,
  NULL AS zotlo_overview_event_count_start_paid,
  NULL AS zotlo_overview_revenue_start_paid,
  NULL AS zotlo_overview_event_count_package_upgrate,
  NULL AS zotlo_overview_revenue_package_upgrate,
  NULL AS zotlo_overview_event_count_epin,
  NULL AS zotlo_overview_revenue_epin,
  NULL AS zotlo_overview_event_count_package_upgrade,
  NULL AS zotlo_overview_revenue_package_upgrade,

  SUM(proceeds) AS activity_total_proceeds,
  SUM(sales_count) AS activity_total_sales_count,
  SUM(refund_count) AS activity_total_refund_count
FROM
  superset_revenues
GROUP BY ALL


) non_rltv

# LTV Cohort Revenue d1,3,7,15,30

LEFT JOIN rockads-thirdparty.id1010631459_appsflyer_ds.id1010631459_revenue_ltv rltv
ON
  non_rltv.report_date=rltv.install_date
  AND non_rltv.geo=rltv.country_code
  AND non_rltv.campaign=rltv.campaign
  AND non_rltv.adset=rltv.af_adset
  AND non_rltv.ad=rltv.af_ad
  AND non_rltv.media_source=rltv.media_source
  AND non_rltv.appsflyer_os_id=rltv.appsflyer_os_id


# Zotlo LTV Cohort Revenue d0,1,3,7,15,30

LEFT JOIN rockads-thirdparty.id1010631459_appsflyer_ds.id1010631459_zotlo_revenue_ltv zotlo_rltv
ON
  non_rltv.report_date=zotlo_rltv.install_date
  AND non_rltv.geo=zotlo_rltv.country_code
  AND non_rltv.campaign=zotlo_rltv.campaign
  AND non_rltv.adset=zotlo_rltv.af_adset
  AND non_rltv.ad=zotlo_rltv.af_ad
  AND non_rltv.media_source=zotlo_rltv.media_source
  AND non_rltv.appsflyer_os_id=zotlo_rltv.appsflyer_os_id