config {
  type: "table",
    bigquery: {
    partitionBy: "report_date"
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id1010631459_platforms_merged_metrics_all_cost_geo_unique",
  schema: "id1010631459_appsflyer_ds",
  dependencies: ['id1010631459_combined_metrics_unique_dm'],
  tags: ['appsflyer_id1010631459_main']
}

SELECT
DISTINCT
  IFNULL(metrics_dm.report_date, cost_dm.report_date) AS report_date,
  IFNULL(metrics_dm.app_id, cost_dm.app_id) AS app_id,
  IFNULL(metrics_dm.geo, cost_dm.geo) AS geo,
  IFNULL(metrics_dm.campaign, cost_dm.campaign) AS campaign,
  IFNULL(metrics_dm.adset, cost_dm.adset) AS adset,
  IFNULL(metrics_dm.ad, cost_dm.ad) AS ad,
  IFNULL(metrics_dm.media_source, cost_dm.media_source) AS media_source,
  IFNULL(metrics_dm.appsflyer_os_id, cost_dm.appsflyer_os_id) AS appsflyer_os_id,
  IFNULL(metrics_dm.vnew, 0) AS vnew,
  IFNULL(metrics_dm.vreturning, 0) AS vreturning,
  IFNULL(metrics_dm.cc_success_total, 0) AS cc_success_total,
  IFNULL(metrics_dm.subscribe, 0) AS subscribe,
  IFNULL(metrics_dm.start_trial, 0) AS start_trial,
  IFNULL(metrics_dm.recurring_payment, 0) AS recurring_payment,
  
  -- Unique event counts 
  IFNULL(metrics_dm.unique_vnew, 0) AS unique_vnew,
  IFNULL(metrics_dm.unique_vreturning, 0) AS unique_vreturning,
  IFNULL(metrics_dm.unique_cc_success_total, 0) AS unique_cc_success_total,
  IFNULL(metrics_dm.unique_subscribe, 0) AS unique_subscribe,
  IFNULL(metrics_dm.unique_start_trial, 0) AS unique_start_trial,
  IFNULL(metrics_dm.unique_recurring_payment, 0) AS unique_recurring_payment,

  IFNULL(metrics_dm.event_revenue, 0) AS event_revenue,
  IFNULL(cost_dm.total_cost, 0) AS total_cost,
  IFNULL(cost_dm.total_clicks, 0) AS total_clicks,
  IFNULL(cost_dm.total_installs, 0) AS total_installs,


  IFNULL(cost_dm.total_impressions, 0) AS total_impressions,
  IFNULL(cost_dm.total_re_attributions, 0) AS total_re_attributions,
  IFNULL(cost_dm.total_re_engagements, 0) AS total_re_engagements,
  IFNULL(cost_dm.total_video_completions, 0) AS total_video_completions,
  IFNULL(cost_dm.total_video_25p_views, 0) AS total_video_25p_views,
  IFNULL(cost_dm.total_video_50p_views, 0) AS total_video_50p_views,
  IFNULL(cost_dm.total_video_75p_views, 0) AS total_video_75p_views,
  IFNULL(cost_dm.fb_total_outbound_clicks, 0) AS fb_total_outbound_clicks,
  IFNULL(cost_dm.fb_total_impressions, 0) AS fb_total_impressions,
  IFNULL(cost_dm.fb_total_impressions, 0) AS fb_total_clicks,
FROM
  `${dataform.projectConfig.vars.rockadsProject}.id1010631459_appsflyer_ds.id1010631459_combined_metrics_unique_dm` metrics_dm
FULL OUTER JOIN
  `${dataform.projectConfig.vars.rockadsProject}.id1010631459_appsflyer_ds.id1010631459_platforms_merged_all_cost_geo` cost_dm
ON
  metrics_dm.report_date=cost_dm.report_date
  AND metrics_dm.app_id=cost_dm.app_id
  AND metrics_dm.geo=cost_dm.geo
  AND metrics_dm.ad=cost_dm.ad
  AND metrics_dm.media_source=cost_dm.media_source
  AND metrics_dm.campaign=cost_dm.campaign
  AND metrics_dm.adset=cost_dm.adset
  AND metrics_dm.appsflyer_os_id=cost_dm.appsflyer_os_id
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY
    report_date,
    app_id,
    geo,
    campaign,
    adset,
    ad,
    media_source,
    CAST(vnew AS STRING),
    CAST(vreturning AS STRING),
    CAST(cc_success_total AS STRING),
    CAST(subscribe AS STRING),
    CAST(start_trial AS STRING),
    CAST(recurring_payment AS STRING),

    CAST(unique_vnew AS STRING),
    CAST(unique_vreturning AS STRING),
    CAST(unique_cc_success_total AS STRING),
    CAST(unique_subscribe AS STRING),
    CAST(unique_start_trial AS STRING),
    CAST(unique_recurring_payment AS STRING),

    CAST(event_revenue AS STRING),
    CAST(total_cost AS STRING),
    CAST(total_clicks AS STRING),
    CAST(total_installs AS STRING),
    CAST(total_impressions AS STRING),
    CAST(total_re_attributions AS STRING),
    CAST(total_re_engagements AS STRING),
    CAST(total_video_completions AS STRING),
    CAST(total_video_25p_views AS STRING),
    CAST(total_video_50p_views AS STRING),
    CAST(total_video_75p_views AS STRING),
    CAST(fb_total_outbound_clicks AS STRING),
    CAST(fb_total_impressions AS STRING),
    CAST(fb_total_impressions AS STRING)

  ORDER BY appsflyer_os_id DESC
) = 1

