config {
  type: "table",
    bigquery: {
    partitionBy: "event_date",
    clusterBy: ["country_code"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id1010631459_revenues",
  schema: "id1010631459_appsflyer_ds",
  dependencies: ['id1010631459_platforms_merged_all_cost_geo'],
  tags: ['appsflyer_id1010631459_main']
}

WITH
  main_raw_data AS (
  SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'id1010631459' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_price'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_price,

    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_revenue'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_revenue,
    SAFE_CAST(NULLIF(event_revenue_usd, '') AS FLOAT64) AS event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.appsflyer.id1010631459_in_app_events`
  WHERE event_time < '${realtime_marketing.realtime_start_ts_calc}'

   UNION ALL
    SELECT
    campaign,
    adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'id1010631459' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    SAFE_CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    SAFE_CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    SAFE_CAST(event_revenue_usd AS FLOAT64) event_revenue
  FROM
    `rockads-thirdparty.realtime_appsflyer_events.id1010631459_events_latest`
  WHERE
  event_time >= '${realtime_marketing.realtime_start_ts_calc}'
  AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
  AND media_source != 'organic'
  
   UNION ALL
 SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'app_source_getcontact' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_price'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_price,

    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_revenue'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_revenue,
    SAFE_CAST(NULLIF(event_revenue_usd, '') AS FLOAT64) AS event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.appsflyer.app_source_getcontact_in_app_events`
    WHERE event_time < '${realtime_marketing.realtime_start_ts_calc}'

       UNION ALL
        SELECT
        campaign,
        adset,
        af_ad,
        af_ad_id,
        CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
        'app_source_getcontact' as appsflyer_os_id,
        country_code,
        DATE(install_time) AS event_date,
        SAFE_CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
        SAFE_CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
        SAFE_CAST(event_revenue_usd AS FLOAT64) event_revenue
      FROM
        `rockads-thirdparty.realtime_appsflyer_events.app_source_getcontact_events_latest`
      WHERE
      event_time >= '${realtime_marketing.realtime_start_ts_calc}'
      AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
      AND media_source != 'organic'

    # Adjust
    UNION ALL
    SELECT
        IF(media_source='Organic', 'ORGANIC', IF(campaign_name='Organic', 'ORGANIC', campaign_name)) as campaign_name,
        IF(campaign_name='Organic', 'ORGANIC',IF(media_source='Organic', 'ORGANIC', IF(adgroup_name='Organic', 'ORGANIC', adgroup_name))) as adgroup_name,
        IF(campaign_name='Organic', 'ORGANIC',IF(media_source='Organic', 'ORGANIC', IF(ad_name='Organic', 'ORGANIC', ad_name))) as ad_name,
        NULL AS  af_ad_id,
        CASE
          WHEN media_source in ('Facebook Installs','Facebook','facebook','restricted') then 'Facebook Ads'
          WHEN media_source = 'Organic' then 'ORGANIC'
         ELSE media_source end as media_source,
        appsflyer_os_id,
        UPPER(country_code) AS country_code,
        DATE(install_time) AS event_date,
        NULL AS event_value_af_price,
        NULL AS event_value_af_revenue,
        SAFE_CAST(revenue_usd AS FLOAT64) event_revenue
      FROM
        `rockads-thirdparty.gtc_adjust_ds.all_events`
      WHERE event_time >= '2026-01-09' and lower(media_source) != 'organic'
    )
SELECT
  *
FROM (
  SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    country_code,
    media_source,
    appsflyer_os_id,
    event_date,
    SUM(
    IF
      (event_value_af_revenue=0,0,event_value_af_price)) AS event_value_af_price,
    SUM(event_value_af_revenue) AS event_value_af_revenue,
    SUM(SAFE_MULTIPLY(CAST(event_revenue AS FLOAT64), 0.7) ) event_revenue
  FROM
    main_raw_data
  GROUP BY
    ALL )