config {
  type: "table",
    bigquery: {
    partitionBy: "report_date"
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "teli_combined_metrics_unique_dm",
  schema: "teli_adjust_ds",
  dependencies: ['teli_event_counts_unique'],
  tags: ['adjust_teli_main']
}

WITH
  appsflyer_count AS (
  SELECT
  DISTINCT
    event_date AS report_date,
    'teli' AS app_id,
    country_code AS geo,
    campaign,
    af_adset as adset,
    af_ad AS ad,
    media_source,
    adjust_os_id,
      SUM(event_count_trial_cancelled)   event_count_trial_cancelled,
      SUM(event_count_subscription_cancelled)       event_count_subscription_cancelled,
      SUM(event_count_trial_started)       event_count_trial_started,
      SUM(event_count_one_time_purchase)       event_count_one_time_purchase,
      SUM(event_count_subscription_renewed)       event_count_subscription_renewed,
      SUM(event_count_subscription_started)       event_count_subscription_started,
      SUM(event_count_subscription_expired)       event_count_subscription_expired,
      SUM(event_count_subscription_changed)       event_count_subscription_changed,


      SUM(unique_event_count_trial_cancelled)       unique_event_count_trial_cancelled,
      SUM(unique_event_count_subscription_cancelled)       unique_event_count_subscription_cancelled,
      SUM(unique_event_count_trial_started)       unique_event_count_trial_started,
      SUM(unique_event_count_one_time_purchase)       unique_event_count_one_time_purchase,
      SUM(unique_event_count_subscription_renewed)       unique_event_count_subscription_renewed,
      SUM(unique_event_count_subscription_started)       unique_event_count_subscription_started,
      SUM(unique_event_count_subscription_expired)       unique_event_count_subscription_expired,
      SUM(unique_event_count_subscription_changed)       unique_event_count_subscription_changed,


      SUM(revenue_trial_cancelled)       revenue_trial_cancelled,
      SUM(revenue_subscription_cancelled)       revenue_subscription_cancelled,
      SUM(revenue_trial_started)       revenue_trial_started,
      SUM(revenue_one_time_purchase)       revenue_one_time_purchase,
      SUM(revenue_subscription_renewed)       revenue_subscription_renewed,
      SUM(revenue_subscription_started)       revenue_subscription_started,
      SUM(revenue_subscription_expired)       revenue_subscription_expired,
      SUM(revenue_subscription_changed)       revenue_subscription_changed,

  FROM
    `${dataform.projectConfig.vars.rockadsProject}.teli_adjust_ds.teli_event_counts_unique`
  GROUP BY ALL
),
  revenues AS (
  SELECT
    DISTINCT
    event_date AS report_date,
    'teli' AS app_id,
    country_code AS geo,
    campaign,
    af_adset as adset,
    af_ad AS ad,
    media_source,
    adjust_os_id,
    SUM(event_revenue) event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.teli_adjust_ds.teli_revenues`
  GROUP BY ALL
)

SELECT
  IFNULL(af_counts.report_date, rvns.report_date) AS report_date,
  IFNULL(af_counts.app_id, rvns.app_id) AS app_id,
  IFNULL(af_counts.geo, rvns.geo) AS geo,
  IFNULL(af_counts.campaign, rvns.campaign) AS campaign,
  IFNULL(af_counts.adset, rvns.adset) AS adset,
  IFNULL(af_counts.ad, rvns.ad) AS ad,
  IFNULL(af_counts.media_source, rvns.media_source) AS media_source,
  IFNULL(af_counts.adjust_os_id, rvns.adjust_os_id) AS adjust_os_id,

  # event counts
  IFNULL(af_counts.event_count_trial_cancelled , 0)      trial_cancelled ,
  IFNULL(af_counts.event_count_subscription_cancelled, 0)      subscription_cancelled ,
  IFNULL(af_counts.event_count_trial_started, 0)       trial_started ,
  IFNULL(af_counts.event_count_one_time_purchase, 0)       one_time_purchase ,
  IFNULL(af_counts.event_count_subscription_renewed, 0)       subscription_renewed ,
  IFNULL(af_counts.event_count_subscription_started, 0)       subscription_started ,
  IFNULL(af_counts.event_count_subscription_expired, 0)       subscription_expired ,
  IFNULL(af_counts.event_count_subscription_changed, 0)       subscription_changed ,

  # unique event counts
  IFNULL(af_counts.unique_event_count_trial_cancelled, 0)       unique_trial_cancelled,
  IFNULL(af_counts.unique_event_count_subscription_cancelled, 0)       unique_subscription_cancelled,
  IFNULL(af_counts.unique_event_count_trial_started, 0)       unique_trial_started,
  IFNULL(af_counts.unique_event_count_one_time_purchase, 0)       unique_one_time_purchase,
  IFNULL(af_counts.unique_event_count_subscription_renewed, 0)       unique_subscription_renewed,
  IFNULL(af_counts.unique_event_count_subscription_started, 0)       unique_subscription_started,
  IFNULL(af_counts.unique_event_count_subscription_expired, 0)       unique_subscription_expired,
  IFNULL(af_counts.unique_event_count_subscription_changed, 0)       unique_subscription_changed,

  # revenue
  IFNULL(af_counts.revenue_trial_cancelled, 0)       revenue_trial_cancelled,
  IFNULL(af_counts.revenue_subscription_cancelled, 0)       revenue_subscription_cancelled,
  IFNULL(af_counts.revenue_trial_started, 0)       revenue_trial_started,
  IFNULL(af_counts.revenue_one_time_purchase, 0)       revenue_one_time_purchase,
  IFNULL(af_counts.revenue_subscription_renewed, 0)       revenue_subscription_renewed,
  IFNULL(af_counts.revenue_subscription_started, 0)       revenue_subscription_started,
  IFNULL(af_counts.revenue_subscription_expired, 0)       revenue_subscription_expired,
  IFNULL(af_counts.revenue_subscription_changed, 0)       revenue_subscription_changed,

  IFNULL(rvns.event_revenue, 0) AS event_revenue,
FROM
  appsflyer_count af_counts
FULL OUTER JOIN
  revenues rvns
ON
  af_counts.report_date=rvns.report_date
  AND af_counts.app_id=rvns.app_id
  AND af_counts.geo=rvns.geo
  AND af_counts.ad=rvns.ad
  AND af_counts.media_source=rvns.media_source
  AND af_counts.campaign=rvns.campaign
  AND af_counts.adset=rvns.adset
  AND af_counts.adjust_os_id=rvns.adjust_os_id