config {
  type: "table",
    bigquery: {
    partitionBy: "report_date"
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id1662905686_organic_combined_metrics_unique_dm",
  schema: "id1662905686_appsflyer_ds",
  dependencies: ['id1662905686_organic_event_counts_unique'],
  tags: ['appsflyer_id1662905686_main']
}

SELECT DISTINCT   report_date,
  app_id,
  geo,
  campaign,
  adset,
  ad,
  CASE WHEN media_source = 'facebook' then 'Facebook Ads' ELSE media_source end as media_source,
  appsflyer_os_id,
  CAST(Null AS STRING) AS thumbnail_url,
  CAST(Null AS STRING) AS video_url,
  SUM(rc_trial_converted_event) AS rc_trial_converted_event,
  SUM(rc_renewal_event) AS rc_renewal_event,
  SUM(rc_cancellation_event) AS rc_cancellation_event,
  SUM(rc_trial_started_event) AS rc_trial_started_event,
  SUM(rc_trial_cancelled_event) AS rc_trial_cancelled_event,
  SUM(rc_initial_purchase_event) AS rc_initial_purchase_event,
  SUM(rc_non_subscription_purchase_event) AS rc_non_subscription_purchase_event,
  SUM(rc_expiration_event) AS rc_expiration_event,
  SUM(rc_billing_issue_event) AS rc_billing_issue_event,
  SUM(rc_product_change_event) AS rc_product_change_event,
  NULL AS af_purchase,
  NULL AS package_purchase,

  SUM(unique_rc_trial_converted_event) AS unique_rc_trial_converted_event,
  SUM(unique_rc_renewal_event) AS unique_rc_renewal_event,
  SUM(unique_rc_cancellation_event) AS unique_rc_cancellation_event,
  SUM(unique_rc_trial_started_event) AS unique_rc_trial_started_event,
  SUM(unique_rc_trial_cancelled_event) AS unique_rc_trial_cancelled_event,
  SUM(unique_rc_initial_purchase_event) AS unique_rc_initial_purchase_event,
  SUM(unique_rc_non_subscription_purchase_event) AS unique_rc_non_subscription_purchase_event,
  SUM(unique_rc_expiration_event) AS unique_rc_expiration_event,
  SUM(unique_rc_billing_issue_event) AS unique_rc_billing_issue_event,
  SUM(unique_rc_product_change_event) AS unique_rc_product_change_event,
  NULL AS unique_af_purchase,
  NULL AS unique_package_purchase,

      -- Revenues
    SUM(revenue_rc_trial_converted_event) revenue_rc_trial_converted_event,
    SUM(revenue_rc_renewal_event) revenue_rc_renewal_event,
    SUM(revenue_rc_cancellation_event) revenue_rc_cancellation_event,
    SUM(revenue_rc_trial_started_event) revenue_rc_trial_started_event,
    SUM(revenue_rc_trial_cancelled_event) revenue_rc_trial_cancelled_event,
    SUM(revenue_rc_initial_purchase_event) revenue_rc_initial_purchase_event,
    SUM(revenue_rc_non_subscription_purchase_event) revenue_rc_non_subscription_purchase_event,
    SUM(revenue_rc_expiration_event) revenue_rc_expiration_event,
    SUM(revenue_rc_billing_issue_event) revenue_rc_billing_issue_event,
    SUM(revenue_rc_product_change_event) revenue_rc_product_change_event,

  SUM(event_revenue) AS event_revenue,
  Null AS total_cost,
  Null AS total_clicks,
  Null AS total_installs,
  Null AS total_impressions,
  Null AS total_re_attributions,
  Null AS total_re_engagements,
  Null AS total_video_completions,
  Null AS total_video_25p_views,
  Null AS total_video_50p_views,
  Null AS total_video_75p_views,
  CAST(NULL AS NUMERIC) AS fb_total_outbound_clicks,
  CAST(NULL AS NUMERIC) AS fb_total_impressions,
  CAST(NULL AS NUMERIC) AS fb_total_clicks,
FROM (
WITH
  appsflyer_count AS (
  SELECT
  DISTINCT
    event_date AS report_date,
    'id1662905686' AS app_id,
    country_code AS geo,
    campaign,
    af_adset as adset,
    af_ad AS ad,
    media_source,
    appsflyer_os_id,
    SUM(event_count_rc_trial_converted_event) event_count_rc_trial_converted_event,
    SUM(event_count_rc_renewal_event) event_count_rc_renewal_event,
    SUM(event_count_rc_cancellation_event) event_count_rc_cancellation_event,
    SUM(event_count_rc_trial_started_event) event_count_rc_trial_started_event,
    SUM(event_count_rc_trial_cancelled_event) event_count_rc_trial_cancelled_event,
    SUM(event_count_rc_initial_purchase_event) event_count_rc_initial_purchase_event,
    SUM(event_count_rc_non_subscription_purchase_event) event_count_rc_non_subscription_purchase_event,
    SUM(event_count_rc_expiration_event) event_count_rc_expiration_event,
    SUM(event_count_rc_billing_issue_event) event_count_rc_billing_issue_event,
    SUM(event_count_rc_product_change_event) event_count_rc_product_change_event,

    SUM(unique_event_count_rc_trial_converted_event) unique_event_count_rc_trial_converted_event,
    SUM(unique_event_count_rc_renewal_event) unique_event_count_rc_renewal_event,
    SUM(unique_event_count_rc_cancellation_event) unique_event_count_rc_cancellation_event,
    SUM(unique_event_count_rc_trial_started_event) unique_event_count_rc_trial_started_event,
    SUM(unique_event_count_rc_trial_cancelled_event) unique_event_count_rc_trial_cancelled_event,
    SUM(unique_event_count_rc_initial_purchase_event) unique_event_count_rc_initial_purchase_event,
    SUM(unique_event_count_rc_non_subscription_purchase_event) unique_event_count_rc_non_subscription_purchase_event,
    SUM(unique_event_count_rc_expiration_event) unique_event_count_rc_expiration_event,
    SUM(unique_event_count_rc_billing_issue_event) unique_event_count_rc_billing_issue_event,
    SUM(unique_event_count_rc_product_change_event) unique_event_count_rc_product_change_event,

    SUM(revenue_rc_trial_converted_event) revenue_rc_trial_converted_event,
    SUM(revenue_rc_renewal_event) revenue_rc_renewal_event,
    SUM(revenue_rc_cancellation_event) revenue_rc_cancellation_event,
    SUM(revenue_rc_trial_started_event) revenue_rc_trial_started_event,
    SUM(revenue_rc_trial_cancelled_event) revenue_rc_trial_cancelled_event,
    SUM(revenue_rc_initial_purchase_event) revenue_rc_initial_purchase_event,
    SUM(revenue_rc_non_subscription_purchase_event) revenue_rc_non_subscription_purchase_event,
    SUM(revenue_rc_expiration_event) revenue_rc_expiration_event,
    SUM(revenue_rc_billing_issue_event) revenue_rc_billing_issue_event,
    SUM(revenue_rc_product_change_event) revenue_rc_product_change_event,

  FROM
    `${dataform.projectConfig.vars.rockadsProject}.id1662905686_appsflyer_ds.id1662905686_organic_event_counts_unique`
  GROUP BY ALL
),
  revenues AS (
  SELECT
    DISTINCT
    event_date AS report_date,
    'id1662905686' AS app_id,
    country_code AS geo,
    campaign,
    af_adset as adset,
    af_ad AS ad,
    media_source,
    appsflyer_os_id,
    SUM(event_revenue) event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.id1662905686_appsflyer_ds.id1662905686_organic_revenues`
  GROUP BY ALL
)

SELECT
  IFNULL(af_counts.report_date, rvns.report_date) AS report_date,
  IFNULL(af_counts.app_id, rvns.app_id) AS app_id,
  IFNULL(af_counts.geo, rvns.geo) AS geo,
  IFNULL(af_counts.campaign, rvns.campaign) AS campaign,
  IFNULL(af_counts.adset, rvns.adset) AS adset,
  IFNULL(af_counts.ad, rvns.ad) AS ad,
  IFNULL(af_counts.media_source, rvns.media_source) AS media_source,
  IFNULL(af_counts.appsflyer_os_id, rvns.appsflyer_os_id) AS appsflyer_os_id,
  IFNULL(af_counts.event_count_rc_trial_converted_event, 0) AS rc_trial_converted_event,
  IFNULL(af_counts.event_count_rc_renewal_event, 0) AS rc_renewal_event,
  IFNULL(af_counts.event_count_rc_cancellation_event, 0) AS rc_cancellation_event,
  IFNULL(af_counts.event_count_rc_trial_started_event, 0) AS rc_trial_started_event,
  IFNULL(af_counts.event_count_rc_trial_cancelled_event, 0) AS rc_trial_cancelled_event,
  IFNULL(af_counts.event_count_rc_initial_purchase_event, 0) AS rc_initial_purchase_event,
  IFNULL(af_counts.event_count_rc_non_subscription_purchase_event, 0) AS rc_non_subscription_purchase_event,
  IFNULL(af_counts.event_count_rc_expiration_event, 0) AS rc_expiration_event,
  IFNULL(af_counts.event_count_rc_billing_issue_event, 0) AS rc_billing_issue_event,
  IFNULL(af_counts.event_count_rc_product_change_event, 0) AS rc_product_change_event,

  -- Unique event counts
  IFNULL(af_counts.unique_event_count_rc_trial_converted_event, 0) AS unique_rc_trial_converted_event,
  IFNULL(af_counts.unique_event_count_rc_renewal_event, 0) AS unique_rc_renewal_event,
  IFNULL(af_counts.unique_event_count_rc_cancellation_event, 0) AS unique_rc_cancellation_event,
  IFNULL(af_counts.unique_event_count_rc_trial_started_event, 0) AS unique_rc_trial_started_event,
  IFNULL(af_counts.unique_event_count_rc_trial_cancelled_event, 0) AS unique_rc_trial_cancelled_event,
  IFNULL(af_counts.unique_event_count_rc_initial_purchase_event, 0) AS unique_rc_initial_purchase_event,
  IFNULL(af_counts.unique_event_count_rc_non_subscription_purchase_event, 0) AS unique_rc_non_subscription_purchase_event,
  IFNULL(af_counts.unique_event_count_rc_expiration_event, 0) AS unique_rc_expiration_event,
  IFNULL(af_counts.unique_event_count_rc_billing_issue_event, 0) AS unique_rc_billing_issue_event,
  IFNULL(af_counts.unique_event_count_rc_product_change_event, 0) AS unique_rc_product_change_event,

  -- Revenues
  IFNULL(af_counts.revenue_rc_trial_converted_event, 0) AS revenue_rc_trial_converted_event,
  IFNULL(af_counts.revenue_rc_renewal_event, 0) AS revenue_rc_renewal_event,
  IFNULL(af_counts.revenue_rc_cancellation_event, 0) AS revenue_rc_cancellation_event,
  IFNULL(af_counts.revenue_rc_trial_started_event, 0) AS revenue_rc_trial_started_event,
  IFNULL(af_counts.revenue_rc_trial_cancelled_event, 0) AS revenue_rc_trial_cancelled_event,
  IFNULL(af_counts.revenue_rc_initial_purchase_event, 0) AS revenue_rc_initial_purchase_event,
  IFNULL(af_counts.revenue_rc_non_subscription_purchase_event, 0) AS revenue_rc_non_subscription_purchase_event,
  IFNULL(af_counts.revenue_rc_expiration_event, 0) AS revenue_rc_expiration_event,
  IFNULL(af_counts.revenue_rc_billing_issue_event, 0) AS revenue_rc_billing_issue_event,
  IFNULL(af_counts.revenue_rc_product_change_event, 0) AS revenue_rc_product_change_event,

  IFNULL(rvns.event_revenue, 0) AS event_revenue,
FROM
  appsflyer_count af_counts
FULL OUTER JOIN
  revenues rvns
ON
  af_counts.report_date=rvns.report_date
  AND af_counts.app_id=rvns.app_id
  AND af_counts.geo=rvns.geo
  AND af_counts.ad=rvns.ad
  AND af_counts.media_source=rvns.media_source
  AND af_counts.campaign=rvns.campaign
  AND af_counts.adset=rvns.adset
  AND af_counts.appsflyer_os_id=rvns.appsflyer_os_id
)
GROUP BY ALL