config {
  type: "table",
    bigquery: {
    partitionBy: "event_date",
    clusterBy: ["country_code"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id1662905686_organic_revenues",
  schema: "id1662905686_appsflyer_ds",
  tags: ['appsflyer_id1662905686_main']
}

WITH
  main_raw_data AS (
  SELECT
    'ORGANIC' as campaign,
    'ORGANIC' as af_adset,
    'ORGANIC' as af_ad,
    'ORGANIC' as af_ad_id,
    'ORGANIC' as media_source,
    'id1662905686' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.appsflyer.id1662905686_organic_in_app_events`
   WHERE event_time < '${realtime_marketing.realtime_start_ts_calc}'

  UNION ALL
    SELECT
    'ORGANIC' as campaign,
    'ORGANIC' as af_adset,
    'ORGANIC' as af_ad,
    'ORGANIC' as af_ad_id,
    'ORGANIC' as media_source,
    'id1662905686' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `rockads-thirdparty.realtime_appsflyer_events.id1662905686_events_latest`
    WHERE
        event_time >= '${realtime_marketing.realtime_start_ts_calc}'
        AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
        AND media_source = 'organic'
        
  UNION ALL
     SELECT
        'ORGANIC' as campaign,
        'ORGANIC' as af_adset,
        'ORGANIC' as af_ad,
        'ORGANIC' as af_ad_id,
        'ORGANIC' as media_source,
        'app_roboco_android' as appsflyer_os_id,
        country_code,
        DATE(install_time) AS event_date,
        CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
        CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
        CAST(event_revenue AS FLOAT64) event_revenue
      FROM
        `${dataform.projectConfig.vars.rockadsProject}.appsflyer.app_roboco_android_organic_in_app_events`
      WHERE event_time < '${realtime_marketing.realtime_start_ts_calc}'

      UNION ALL
         SELECT
            'ORGANIC' as campaign,
            'ORGANIC' as af_adset,
            'ORGANIC' as af_ad,
            'ORGANIC' as af_ad_id,
            'ORGANIC' as media_source,
            'app_roboco_android' as appsflyer_os_id,
            country_code,
            DATE(install_time) AS event_date,
            CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
            CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
            CAST(event_revenue AS FLOAT64) event_revenue
        FROM
          `rockads-thirdparty.realtime_appsflyer_events.app_roboco_android_events_latest`
        WHERE
            event_time >= '${realtime_marketing.realtime_start_ts_calc}'
            AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
            AND media_source = 'organic'
        
    )
SELECT
  *
FROM (
  SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    country_code,
    media_source,
    appsflyer_os_id,
    event_date,
    SUM(
    IF
      (event_value_af_revenue=0,0,event_value_af_price)) AS event_value_af_price,
    SUM(event_value_af_revenue) AS event_value_af_revenue,
    SUM(CAST(event_revenue AS FLOAT64)) event_revenue
  FROM
    main_raw_data
  GROUP BY
    ALL )