config {
  type: "table",
    bigquery: {
    partitionBy: "event_date",
    clusterBy: ["country_code"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6738388891_activity_revenues",
  schema: "id6738388891_appsflyer_ds",
  tags: ['appsflyer_id6738388891_main']
}

WITH
  main_raw_data AS (
  SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'id6738388891' as appsflyer_os_id,
    country_code,
    DATE(event_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.appsflyer_airbyte.ai_cleaner_in_app_events`
    where app_id = 'id6738388891' AND DATE(event_time) < '2025-10-13'
  
    UNION ALL
   SELECT
    IF(campaign='',NULL, campaign) AS campaign,
    IF(af_adset='',NULL, af_adset) AS af_adset,
    IF(af_ad ='',NULL, af_ad) AS af_ad,
    IF(af_ad_id='',NULL, af_ad_id) AS af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE IF(media_source='',NULL, media_source) end as media_source,
    'id6738388891' as appsflyer_os_id,
    country_code,
    DATE(event_time) AS event_date,
    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_price'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_price,

    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_revenue'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_revenue,
    SAFE_CAST(NULLIF(event_revenue, '') AS FLOAT64) AS event_revenue
  FROM
    `rockads-thirdparty.appsflyer_airflow.id6738388891_in_app_events`
    where DATE(event_time) >= '2025-10-13' AND event_time < '${realtime_marketing.realtime_start_ts_calc}'
    
  UNION ALL
    SELECT
    campaign,
    adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'id6738388891' as appsflyer_os_id,
    country_code,
    DATE(event_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `rockads-thirdparty.realtime_appsflyer_events.id6738388891_events_latest`
  WHERE
  event_time >= '${realtime_marketing.realtime_start_ts_calc}'
  AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
  AND media_source != 'organic'
    
    )
SELECT
  *
FROM (
  SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    country_code,
    media_source,
    appsflyer_os_id,
    event_date,
    SUM(
    IF
      (event_value_af_revenue=0,0,event_value_af_price)) AS activity_event_value_af_price,
    SUM(event_value_af_revenue) AS activity_event_value_af_revenue,
    SUM(CAST(event_revenue AS FLOAT64)) activity_event_revenue
  FROM
    main_raw_data
  GROUP BY
    ALL )