config {
  type: "table",
    bigquery: {
    partitionBy: "event_date",
    clusterBy: ["country_code"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6738388891_organic_event_counts_unique",
  schema: "id6738388891_appsflyer_ds",
  dependencies: ['id6738388891_organic_revenues'],
  tags: ['appsflyer_id6738388891_main']
}

WITH main_raw_data AS (
SELECT 'ORGANIC' as campaign, 'ORGANIC' as af_adset, 'ORGANIC' as af_ad,'ORGANIC' as af_ad_id, event_name,'ORGANIC' as media_source,
'id6738388891' as appsflyer_os_id,
country_code,customer_user_id,
event_revenue,
DATE(install_time) as event_date,

 FROM `${dataform.projectConfig.vars.rockadsProject}.appsflyer_airbyte.ai_cleaner_organic_in_app_events` 
WHERE event_time < '${realtime_marketing.realtime_start_ts_calc}'

UNION ALL
SELECT 'ORGANIC' as campaign, 'ORGANIC' as af_adset, 'ORGANIC' as af_ad,'ORGANIC' as af_ad_id, event_name,'ORGANIC' as media_source,
'id6738388891' as appsflyer_os_id,
country_code,customer_user_id,
SAFE_CAST(event_revenue AS STRING) AS event_revenue,
DATE(install_time) as event_date,
FROM
`rockads-thirdparty.realtime_appsflyer_events.id6738388891_events_latest`
WHERE
    event_time >= '${realtime_marketing.realtime_start_ts_calc}'
    AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
    AND media_source = 'organic'
    
)
SELECT * FROM (
SELECT campaign, af_adset, af_ad, af_ad_id, country_code,
media_source, appsflyer_os_id, event_name,
event_date,
count(event_name) AS event_count,
count(distinct customer_user_id) AS unique_event_count,
sum(CAST(event_revenue AS FLOAT64)) AS revenue,
FROM main_raw_data 
GROUP BY ALL
)
PIVOT (
  MAX(event_count) as event_count, 
  MAX(unique_event_count)  as unique_event_count,
  MAX(revenue)  as revenue FOR event_name IN (
    'paywallShowed',
    'paymentInit',
    'rc_renewal_event',
    'rc_trial_converted_event',
    'rc_expiration_event',
    'rc_cancellation_event',
    'rc_billing_issue_event',
    'rc_initial_purchase_event',
    'rc_product_change_event',
    'rc_trial_started_event',
    'rc_trial_cancelled_event',
    'WebToAppInstall',
    'rc_non_subscription_purchase_event'
  )
)