
config {
  type: "table",
    bigquery: {
    partitionBy: "report_date"
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "teli_activity_union",
  schema: "teli_adjust_ds",
  dependencies: ['teli_organic_activity_combined_metrics_unique_dm', 'teli_activity_combined_metrics_unique_dm'],
  tags: ['adjust_teli_main']
}

  SELECT
    report_date,
    app_id,
    geo,
    campaign,
    af_adset,
    ad,
    media_source,
    adjust_os_id,
    -- Total event revenues
      SUM(activity_revenue_trial_cancelled) AS       activity_revenue_trial_cancelled,
      SUM(activity_revenue_subscription_cancelled) AS       activity_revenue_subscription_cancelled,
      SUM(activity_revenue_trial_started) AS       activity_revenue_trial_started,
      SUM(activity_revenue_one_time_purchase) AS       activity_revenue_one_time_purchase,
      SUM(activity_revenue_subscription_renewed) AS       activity_revenue_subscription_renewed,
      SUM(activity_revenue_subscription_started) AS       activity_revenue_subscription_started,
      SUM(activity_revenue_subscription_expired) AS       activity_revenue_subscription_expired,
      SUM(activity_revenue_subscription_changed) AS       activity_revenue_subscription_changed,

        SUM(activity_trial_cancelled) AS activity_trial_cancelled,
        SUM(activity_subscription_cancelled) AS activity_subscription_cancelled,
        SUM(activity_trial_started) AS activity_trial_started,
        SUM(activity_one_time_purchase) AS activity_one_time_purchase,
        SUM(activity_subscription_renewed) AS activity_subscription_renewed,
        SUM(activity_subscription_started) AS activity_subscription_started,
        SUM(activity_subscription_expired) AS activity_subscription_expired,
        SUM(activity_subscription_changed) AS activity_subscription_changed,

    -- Revenue
    SUM(activity_event_revenue) AS activity_event_revenue
  FROM(
    SELECT *
  FROM
    ${dataform.projectConfig.vars.rockadsProject}.teli_adjust_ds.teli_activity_combined_metrics_unique_dm
  UNION ALL
  SELECT
    *
  FROM
    ${dataform.projectConfig.vars.rockadsProject}.teli_adjust_ds.teli_organic_activity_combined_metrics_unique_dm
  )
  GROUP BY
    ALL