config {
  type: "table",
    bigquery: {
    partitionBy: "event_date",
    clusterBy: ["country_code"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6473276045_activity_event_counts_unique",
  schema: "id6473276045_appsflyer_ds",
  dependencies: ['id6473276045_activity_revenues'],
  tags: ['appsflyer_id6473276045_main']
}
WITH currency_rates AS (
SELECT
      date,
      base_currency,
      relative_currency,
      currency_rate
FROM `rockads-thirdparty.mapping_tables.currency_rates_*`
WHERE _TABLE_SUFFIX >='20250101'
),
main_raw_data AS (
SELECT  campaign, af_adset, af_ad, af_ad_id, event_name,IF(media_source = 'restricted', 'Facebook Ads', media_source) as media_source,
'id6473276045' as appsflyer_os_id,
installed_country_code as country_code,customer_user_id,
SAFE_DIVIDE(CAST(event_revenue AS FLOAT64), cr.currency_rate) as event_revenue,
DATE(event_time) as event_date,
FROM `${dataform.projectConfig.vars.rockadsProject}.appsflyer.id6473276045_in_app_events`isdr

  LEFT JOIN currency_rates cr ON DATE(isdr.event_time) = cr.date AND
    IFNULL(event_revenue_currency, IFNULL(CAST(JSON_EXTRACT_SCALAR(isdr.event_value, '$.af_currency')AS STRING), 'USD')) = cr.relative_currency

  LEFT JOIN (
    SELECT
      appsflyer_id,
      country_code as installed_country_code
    FROM
      `rockads-thirdparty.appsflyer.id6473276045_in_app_events`
    QUALIFY ROW_NUMBER() OVER(PARTITION BY appsflyer_id ORDER BY event_time ASC) = 1
    ) usr_ct on isdr.appsflyer_id=usr_ct.appsflyer_id

WHERE event_time < '${realtime_marketing.realtime_start_ts_calc}'

UNION ALL
SELECT
  IF(campaign = '', NULL, campaign) AS campaign,
  IF(adset    = '', NULL, adset)    AS af_adset,
  IF(af_ad    = '', NULL, af_ad)    AS af_ad,
  IF(af_ad_id = '', NULL, af_ad_id) AS af_ad_id,
  event_name,
  IF(media_source = 'restricted', 'Facebook Ads', IF(media_source = '', NULL, media_source)) AS media_source,
  'id6473276045' AS appsflyer_os_id,
  country_code,
  customer_user_id,
  SAFE_DIVIDE(CAST(event_revenue AS FLOAT64), cr.currency_rate) as event_revenue,
  DATE(event_time) AS event_date
FROM `rockads-thirdparty.realtime_appsflyer_events.id6473276045_events_latest`isdr

  LEFT JOIN currency_rates cr ON DATE(isdr.event_time) = cr.date AND
    IFNULL(event_revenue_currency, IFNULL(CAST(JSON_EXTRACT_SCALAR(isdr.event_value, '$.af_currency')AS STRING), 'USD')) = cr.relative_currency

  LEFT JOIN (
    SELECT
      appsflyer_id,
      country_code as installed_country_code
    FROM
      `rockads-thirdparty.appsflyer.id6473276045_in_app_events`
    QUALIFY ROW_NUMBER() OVER(PARTITION BY appsflyer_id ORDER BY event_time ASC) = 1
    ) usr_ct on isdr.appsflyer_id=usr_ct.appsflyer_id

WHERE
    event_time >= '${realtime_marketing.realtime_start_ts_calc}'
    AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
  AND media_source != 'organic'

UNION ALL 
SELECT  campaign, af_adset, af_ad, af_ad_id, event_name,IF(media_source = 'restricted', 'Facebook Ads', media_source) as media_source,
'io_esim' as appsflyer_os_id,
installed_country_code as country_code,customer_user_id,
SAFE_DIVIDE(CAST(event_revenue AS FLOAT64), cr.currency_rate) as event_revenue,
DATE(event_time) as event_date,
FROM `${dataform.projectConfig.vars.rockadsProject}.appsflyer.io_esim_in_app_events`isdr

  LEFT JOIN currency_rates cr ON DATE(isdr.event_time) = cr.date AND
    IFNULL(event_revenue_currency, IFNULL(CAST(JSON_EXTRACT_SCALAR(isdr.event_value, '$.af_currency')AS STRING), 'USD')) = cr.relative_currency

  LEFT JOIN (
    SELECT
      appsflyer_id,
      country_code as installed_country_code
    FROM
      `rockads-thirdparty.appsflyer.io_esim_in_app_events`
    QUALIFY ROW_NUMBER() OVER(PARTITION BY appsflyer_id ORDER BY event_time ASC) = 1
    ) usr_ct on isdr.appsflyer_id=usr_ct.appsflyer_id
 
 WHERE event_time < '${realtime_marketing.realtime_start_ts_calc}'

UNION ALL
SELECT
  IF(campaign = '', NULL, campaign) AS campaign,
  IF(adset    = '', NULL, adset)    AS af_adset,
  IF(af_ad    = '', NULL, af_ad)    AS af_ad,
  IF(af_ad_id = '', NULL, af_ad_id) AS af_ad_id,
  event_name,
  IF(media_source = 'restricted', 'Facebook Ads', IF(media_source = '', NULL, media_source)) AS media_source,
  'io_esim' AS appsflyer_os_id,
  country_code,
  customer_user_id,
  SAFE_DIVIDE(CAST(event_revenue AS FLOAT64), cr.currency_rate) as event_revenue,
  DATE(event_time) AS event_date
FROM `rockads-thirdparty.realtime_appsflyer_events.io_esim_events_latest`isdr

  LEFT JOIN currency_rates cr ON DATE(isdr.event_time) = cr.date AND
    IFNULL(event_revenue_currency, IFNULL(CAST(JSON_EXTRACT_SCALAR(isdr.event_value, '$.af_currency')AS STRING), 'USD')) = cr.relative_currency

  LEFT JOIN (
    SELECT
      appsflyer_id,
      country_code as installed_country_code
    FROM
      `rockads-thirdparty.appsflyer.io_esim_in_app_events`
    QUALIFY ROW_NUMBER() OVER(PARTITION BY appsflyer_id ORDER BY event_time ASC) = 1
    ) usr_ct on isdr.appsflyer_id=usr_ct.appsflyer_id

WHERE
    event_time >= '${realtime_marketing.realtime_start_ts_calc}'
    AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
  AND media_source != 'organic'

)
SELECT * FROM (
SELECT campaign, af_adset, af_ad, af_ad_id, country_code,
media_source, appsflyer_os_id, event_name,
event_date,
count(event_name) AS event_count,
count(distinct customer_user_id) AS unique_event_count,
sum(CAST(event_revenue AS FLOAT64)) AS revenue,
FROM main_raw_data 
GROUP BY ALL
)
PIVOT (
  MAX(event_count) as activity_event_count,
  MAX(unique_event_count)  as activity_unique_event_count,
  MAX(revenue) as activity_revenue FOR event_name IN (
    'paywallShowed',
    'paymentInit',
    'rc_renewal_event',
    'rc_trial_converted_event',
    'rc_expiration_event',
    'rc_cancellation_event',
    'rc_billing_issue_event',
    'rc_initial_purchase_event',
    'rc_product_change_event',
    'rc_trial_started_event',
    'rc_trial_cancelled_event',
    'WebToAppInstall',
    'rc_non_subscription_purchase_event',
    'af_purchase',
    'package_purchase',
    'zt_payment_succes'
  )
)