config {
  type: "table",
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "facebook_ad_business_names",
  schema: "mapping_tables",
  tags: ['facebook']
}

WITH
  new_or_update AS (
  SELECT
    DISTINCT account_id,
    account_name,
    business_id,
    business_name
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.facebook.facebook_ad_accounts` ),
  history AS (
  SELECT
    *
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.mapping_tables.facebook_ad_business_names`
  WHERE
    account_id NOT IN (
    SELECT
      account_id
    FROM
      new_or_update ))
SELECT
  *
FROM
  history
UNION ALL
SELECT
  *
FROM
  new_or_update
