config {
  type: "table",
    bigquery: {
    partitionBy: "install_date"
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6738990592_churney_ltv",
  schema: "id6738990592_appsflyer_ds",
  tags: ['appsflyer_id6738990592_pltv_main']
}

WITH churney_prediction as (

SELECT
  DATE(install_date) AS install_date,
  campaign_name AS campaign,
  media_source,
  platform as operating_system,
  count(distinct user_id) as unique_churney_user_count,
  SUM(cumulative_pltv) AS churney_ltv
FROM
  (WITH
  churney_users AS (
  SELECT
    *
  FROM
    `churney-teknasyon-public.analytics.all_platforms_pltv`
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY prediction_timestamp ASC ) <= 2 ),
appsflyer_users AS (
  WITH
    main_raw_data AS (
    SELECT
      campaign,
      af_adset,
      af_ad,
      af_ad_id,
      event_name,
    IF
      (media_source = 'restricted', 'Facebook Ads', media_source) AS media_source,
      'id6738990592' AS appsflyer_os_id,
      country_code,
      customer_user_id,
      appsflyer_id,
      event_revenue,
      DATE(install_time) AS install_date,
    FROM
      `rockads-thirdparty.appsflyer.id6738990592_in_app_events`
    WHERE
      DATE(event_time) < '2025-06-01'
    UNION ALL
    SELECT
    IF
      (campaign='',NULL, campaign) AS campaign,
    IF
      (af_adset='',NULL, af_adset) AS af_adset,
    IF
      (af_ad='',NULL, af_ad) AS af_ad,
    IF
      (af_ad_id='',NULL, af_ad_id) AS af_ad_id,
      event_name,
    IF
      (media_source = 'restricted', 'Facebook Ads',
      IF
        (media_source='',NULL, media_source)) AS media_source,
      'id6738990592' AS appsflyer_os_id,
      country_code,
      customer_user_id,
      appsflyer_id,
      SAFE_CAST(NULLIF(event_revenue, '') AS STRING) AS event_revenue,
      DATE(install_time) AS install_date,
    FROM
      `rockads-thirdparty.appsflyer_airflow.id6738990592_in_app_events`
    WHERE
      DATE(event_time) >= '2025-06-01'
    UNION ALL
    SELECT
      campaign,
      af_adset,
      af_ad,
      af_ad_id,
      event_name,
    IF
      (media_source = 'restricted', 'Facebook Ads', media_source) AS media_source,
      'com_videoai_effects' AS appsflyer_os_id,
      country_code,
      customer_user_id,
      appsflyer_id,
      event_revenue,
      DATE(install_time) AS install_date,
    FROM
      `rockads-thirdparty.appsflyer.com_videoai_effects_in_app_events`
    WHERE
      DATE(event_time) < '2025-06-12'
    UNION ALL
    SELECT
    IF
      (campaign='',NULL, campaign) AS campaign,
    IF
      (af_adset='',NULL, af_adset) AS af_adset,
    IF
      (af_ad='',NULL, af_ad) AS af_ad,
    IF
      (af_ad_id='',NULL, af_ad_id) AS af_ad_id,
      event_name,
    IF
      (media_source = 'restricted', 'Facebook Ads',
      IF
        (media_source='',NULL, media_source)) AS media_source,
      'com_videoai_effects' AS appsflyer_os_id,
      country_code,
      customer_user_id,
      appsflyer_id,
      SAFE_CAST(NULLIF(event_revenue, '') AS STRING) AS event_revenue,
      DATE(install_time) AS install_date,
    FROM
      `rockads-thirdparty.appsflyer_airflow.com_videoai_effects_in_app_events`
    WHERE
      DATE(event_time) >= '2025-06-12' )
  SELECT
    DISTINCT appsflyer_id,
    customer_user_id,
    install_date
  FROM
    main_raw_data ),
duplicated_data as (
SELECT
  cu.*,
  au.install_date
FROM
  churney_users cu
LEFT JOIN
  appsflyer_users au
ON
  cu.user_id=au.customer_user_id
)
SELECT * , DATE_DIFF(DATE(prediction_timestamp), DATE(install_date), day) as prediction_time_diff
FROM duplicated_data
WHERE DATE_DIFF(DATE(prediction_timestamp), DATE(install_date), day) = 1)
WHERE
  install_date IS NOT NULL
GROUP BY
  ALL
ORDER BY
  1

)
SELECT * FROM churney_prediction