config {
  type: "table",
  bigquery: {
    partitionBy: "install_date"
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6738990592_dt_ltv",
  schema: "id6738990592_appsflyer_ds",
  dependencies: ['id6738990592_churney_ltv'],
  tags: ['appsflyer_id6738990592_pltv_main']
}

WITH dt_pred as (
SELECT * FROM (
SELECT
  install_date,
  operating_system,
  media_source,
  campaign,
  SUM(predicted_ltv) AS dt_ltv,
  _TABLE_SUFFIX AS table_suffix
FROM
  `rockads-thirdparty.appsflyer_ltv.predictions_ltv_30_*`
GROUP BY
  ALL
)
QUALIFY ROW_NUMBER() OVER(PARTITION by install_date, operating_system, media_source, campaign  order by table_suffix desc) = 1

),
real_ltv AS (
  SELECT install_date,
  operating_system,
  media_source,
  campaign,
 sum(ltv_0) as sum_ltv_0, sum(revenue_grand_total) as ltv, sum(user_count_0) as dt_user_count
FROM `rockads-thirdparty.appsflyer_ltv.videa_ltv_prediction_daily_cohorts`
group by ALL
order by install_date desc )

SELECT ap.*, rltv.dt_user_count, rltv.sum_ltv_0, rltv.ltv FROM dt_pred ap
LEFT JOIN real_ltv rltv on rltv.install_date=ap.install_date AND ap.operating_system=rltv.operating_system AND ap.media_source=rltv.media_source AND ap.campaign=rltv.campaign