config {
  type: "table",
    bigquery: {
    partitionBy: "report_date",
    clusterBy: ["media_source"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6741896957_platforms_merged_all_cost_geo",
  schema: "id6741896957_appsflyer_ds",
  dependencies: ['id6741896957_combined_single_all_cost_dm_all_geo'],
  tags: ['appsflyer_id6741896957_main']
}

WITH
  geo_list AS (
  SELECT
    short_code AS geo
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.mapping_tables.countries` ),
  fb_costs AS (
  SELECT
    ad_name AS ad,
    ad_insight_date_start AS report_date,
    campaign_name AS campaign,
    adset_name AS adset,
  IF
    (country='GB', 'UK', country) AS geo,
    'id6741896957' AS app_id,
    'Facebook Ads' AS media_source,
    cast(null as string) as appsflyer_os_id,
    'USD'AS currency,
    SUM(total_spend) AS total_cost,
    SUM(total_outbound_clicks) AS total_outbound_clicks,
    SUM(total_impressions) AS total_impressions,
    SUM(total_clicks) AS total_clicks
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte_datamarts.ads_insights_by_country_merged_773901696065588_stliyco`
  WHERE
    account_id = '1032905726831849'
  GROUP BY
    ALL),
  combined_single_all_cost_dm_all_geo AS (
  SELECT
    *
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.id6741896957_appsflyer_ds.id6741896957_combined_single_all_cost_dm_all_geo` ),
  distinct_combinations AS (
  SELECT
    DISTINCT report_date,
    media_source,
    appsflyer_os_id,
    app_id,
    campaign,
    adset,
    ad,
    currency
  FROM
    fb_costs )
SELECT
  *,
  CAST(NULL AS NUMERIC) AS fb_total_outbound_clicks,
  CAST(NULL AS NUMERIC) AS fb_total_impressions,
  CAST(NULL AS NUMERIC) AS fb_total_clicks,
FROM
  combined_single_all_cost_dm_all_geo
WHERE
  media_source NOT IN ('Facebook Ads')
UNION ALL
SELECT
  IFNULL(fbcs.ad, appsflyer_costs.ad) AS ad,
  IFNULL(fbcs.report_date, appsflyer_costs.report_date) AS report_date,
  IFNULL(fbcs.campaign, appsflyer_costs.campaign) AS campaign,
  IFNULL(fbcs.adset, appsflyer_costs.adset) AS adset,
  IFNULL(fbcs.geo, appsflyer_costs.geo) AS geo,
  IFNULL(fbcs.app_id, appsflyer_costs.app_id) AS app_id,
  IFNULL(fbcs.media_source, appsflyer_costs.media_source) AS media_source,
  IFNULL(fbcs.appsflyer_os_id, appsflyer_costs.appsflyer_os_id) AS appsflyer_os_id,
  IFNULL(fbcs.total_cost, 0) AS total_cost,
  IFNULL(appsflyer_costs.total_installs, 0) AS total_installs,
  IFNULL(appsflyer_costs.total_clicks, 0) AS total_clicks,
  IFNULL(appsflyer_costs.total_impressions, 0) AS total_impressions,
  IFNULL(appsflyer_costs.total_re_attributions, 0) AS total_re_attributions,
  IFNULL(appsflyer_costs.total_re_engagements, 0) AS total_re_engagements,
  IFNULL(appsflyer_costs.total_video_completions, 0) AS total_video_completions,
  IFNULL(appsflyer_costs.total_video_25p_views, 0) AS total_video_25p_views,
  IFNULL(appsflyer_costs.total_video_50p_views, 0) AS total_video_50p_views,
  IFNULL(appsflyer_costs.total_video_75p_views, 0) AS total_video_75p_views,
  IFNULL(fbcs.total_outbound_clicks, 0) AS fb_total_outbound_clicks,
  IFNULL(fbcs.total_impressions, 0) AS fb_total_impressions,
  IFNULL(fbcs.total_clicks, 0) AS fb_total_clicks,

FROM (
  SELECT
    dc.report_date,
    dc.media_source,
    dc.appsflyer_os_id,
    dc.app_id,
    dc.campaign,
    dc.adset,
    dc.ad,
    gl.geo,
    dc.currency,
    IFNULL(ed.total_cost, 0) AS total_cost,
    IFNULL(ed.total_outbound_clicks, 0) AS total_outbound_clicks,
    IFNULL(ed.total_impressions, 0) AS total_impressions,
    IFNULL(ed.total_clicks, 0) AS total_clicks
  FROM
    distinct_combinations dc
  CROSS JOIN
    geo_list gl
  LEFT JOIN
    fb_costs ed
  ON
    dc.report_date = ed.report_date
    AND dc.app_id = ed.app_id
    AND dc.campaign = ed.campaign
    AND dc.adset = ed.adset
    AND dc.ad = ed.ad
    AND dc.currency = ed.currency
    AND gl.geo = ed.geo) fbcs
FULL OUTER JOIN
  (SELECT * FROM combined_single_all_cost_dm_all_geo WHERE media_source IN ('Facebook Ads') ) appsflyer_costs
ON
  fbcs.ad=appsflyer_costs.ad
  AND fbcs.campaign=appsflyer_costs.campaign
  AND fbcs.adset=appsflyer_costs.adset
  AND fbcs.report_date=appsflyer_costs.report_date
  AND fbcs.geo=appsflyer_costs.geo
  AND fbcs.app_id=appsflyer_costs.app_id
  AND fbcs.media_source=appsflyer_costs.media_source