config {
  type: "table",
    bigquery: {
    partitionBy: "event_date",
    clusterBy: ["country_code"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6741896957_revenues",
  schema: "id6741896957_appsflyer_ds",
  dependencies: ['id6741896957_platforms_merged_all_cost_geo'],
  tags: ['appsflyer_id6741896957_main']
}

WITH
  main_raw_data AS (
  SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'id6741896957' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.appsflyer.id6741896957_in_app_events`
    )
SELECT
  *
FROM (
  SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    country_code,
    media_source,
    appsflyer_os_id,
    event_date,
    SUM(
    IF
      (event_value_af_revenue=0,0,event_value_af_price)) AS event_value_af_price,
    SUM(event_value_af_revenue) AS event_value_af_revenue,
    SUM(CAST(event_revenue AS FLOAT64)) event_revenue
  FROM
    main_raw_data
  GROUP BY
    ALL )