config {
  type: "table",
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "ads_audience_reports_by_country_merged_id6443832829",
  schema: "tiktok_airbyte_datamarts",
  tags: ["tiktok_airbyte_etl"]
}

SELECT
  DATE(base.stat_time_day) AS stat_time_day,
  base.ad_id,
  JSON_VALUE(base.metrics, '$.adgroup_id') AS adgroup_id,
  JSON_VALUE(base.metrics, '$.campaign_id') AS campaign_id,
  base.country_code,
  "7272748800069009410" AS advertiser_id,
  JSON_VALUE(base.metrics, '$.ad_name') AS ad_name,
  JSON_VALUE(base.metrics, '$.adgroup_name') AS adgroup_name,
  JSON_VALUE(base.metrics, '$.campaign_name') AS campaign_name,
  IFNULL(video_cover_url, thu.thumbnail_url) AS video_thumbnail_url,
  CASE
    WHEN tiktok_item_id IS NULL THEN preview_url
    WHEN preview_url IS NOT NULL THEN preview_url
    ELSE CONCAT("https://www.tiktok.com/player/v1/", tiktok_item_id, "?id=", tiktok_item_id)
  END AS video_url,
  CAST(JSON_VALUE(base.metrics, '$.spend') AS FLOAT64) AS spend,
  CAST(JSON_VALUE(base.metrics, '$.impressions') AS INT64) AS impressions,
  CAST(JSON_VALUE(base.metrics, '$.clicks') AS INT64) AS clicks,
  CAST(JSON_VALUE(base.metrics, '$.ctr') AS FLOAT64) AS ctr,
  p.app_install AS tiktok_app_install,
  p.purchase AS tiktok_purchase,
  p.conversion AS tiktok_conversion,
  p.start_trial AS tiktok_start_trial
FROM
  `${dataform.projectConfig.vars.rockadsProject}.tiktok_airbyte._7272748800069009410_ads_audience_reports_by_country_daily` base
LEFT JOIN
  `${dataform.projectConfig.vars.rockadsProject}.tiktok_airbyte._7272748800069009410_ads` ads
ON
  base.ad_id = ads.ad_id
LEFT JOIN
  `${dataform.projectConfig.vars.rockadsProject}.tiktok_airbyte._7272748800069009410_creative_assets_videos` assets
ON
  ads.video_id = assets.video_id
LEFT JOIN (
  SELECT
    ad_id,
    thumbnail_url
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.tiktok_spark_thumbnails._7272748800069009410_thumbnails`
) thu
ON
  base.ad_id = thu.ad_id
LEFT JOIN
  `${dataform.projectConfig.vars.rockadsProject}.tiktok.tiktok_purchase_*` p
ON
  DATE(base.stat_time_day) = p.stat_time_day
  AND CAST(base.ad_id AS STRING) = CAST(p.ad_id AS STRING)
  AND base.country_code = p.country_code
  AND CAST(p.advertiser_id AS STRING) = "7272748800069009410"

UNION ALL

SELECT
  DATE(base.stat_time_day) AS stat_time_day,
  base.ad_id,
  JSON_VALUE(base.metrics, '$.adgroup_id') AS adgroup_id,
  JSON_VALUE(base.metrics, '$.campaign_id') AS campaign_id,
  base.country_code,
  "7311957414637830145" AS advertiser_id,
  JSON_VALUE(base.metrics, '$.ad_name') AS ad_name,
  JSON_VALUE(base.metrics, '$.adgroup_name') AS adgroup_name,
  JSON_VALUE(base.metrics, '$.campaign_name') AS campaign_name,
  IFNULL(video_cover_url, thu.thumbnail_url) AS video_thumbnail_url,
  CASE
    WHEN tiktok_item_id IS NULL THEN preview_url
    WHEN preview_url IS NOT NULL THEN preview_url
    ELSE CONCAT("https://www.tiktok.com/player/v1/", tiktok_item_id, "?id=", tiktok_item_id)
  END AS video_url,
  CAST(JSON_VALUE(base.metrics, '$.spend') AS FLOAT64) AS spend,
  CAST(JSON_VALUE(base.metrics, '$.impressions') AS INT64) AS impressions,
  CAST(JSON_VALUE(base.metrics, '$.clicks') AS INT64) AS clicks,
  CAST(JSON_VALUE(base.metrics, '$.ctr') AS FLOAT64) AS ctr,
  p.app_install AS tiktok_app_install,
  p.purchase AS tiktok_purchase,
  p.conversion AS tiktok_conversion,
  p.start_trial AS tiktok_start_trial
FROM
  `${dataform.projectConfig.vars.rockadsProject}.tiktok_airbyte._7311957414637830145_ads_audience_reports_by_country_daily` base
LEFT JOIN
  `${dataform.projectConfig.vars.rockadsProject}.tiktok_airbyte._7311957414637830145_ads` ads
ON
  base.ad_id = ads.ad_id
LEFT JOIN
  `${dataform.projectConfig.vars.rockadsProject}.tiktok_airbyte._7311957414637830145_creative_assets_videos` assets
ON
  ads.video_id = assets.video_id
LEFT JOIN (
  SELECT
    ad_id,
    thumbnail_url
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.tiktok_spark_thumbnails._7311957414637830145_thumbnails`
) thu
ON
  base.ad_id = thu.ad_id
LEFT JOIN
  `${dataform.projectConfig.vars.rockadsProject}.tiktok.tiktok_purchase_*` p
ON
  DATE(base.stat_time_day) = p.stat_time_day
  AND CAST(base.ad_id AS STRING) = CAST(p.ad_id AS STRING)
  AND base.country_code = p.country_code
  AND CAST(p.advertiser_id AS STRING) = "7311957414637830145"

UNION ALL

SELECT
  DATE(base.stat_time_day) AS stat_time_day,
  base.ad_id,
  JSON_VALUE(base.metrics, '$.adgroup_id') AS adgroup_id,
  JSON_VALUE(base.metrics, '$.campaign_id') AS campaign_id,
  base.country_code,
  "7548374257156522001" AS advertiser_id,
  JSON_VALUE(base.metrics, '$.ad_name') AS ad_name,
  JSON_VALUE(base.metrics, '$.adgroup_name') AS adgroup_name,
  JSON_VALUE(base.metrics, '$.campaign_name') AS campaign_name,
  IFNULL(video_cover_url, NULL) AS video_thumbnail_url,
  CASE
    WHEN tiktok_item_id IS NULL THEN preview_url
    WHEN preview_url IS NOT NULL THEN preview_url
    ELSE CONCAT("https://www.tiktok.com/player/v1/", tiktok_item_id, "?id=", tiktok_item_id)
  END AS video_url,
  CAST(JSON_VALUE(base.metrics, '$.spend') AS FLOAT64) AS spend,
  CAST(JSON_VALUE(base.metrics, '$.impressions') AS INT64) AS impressions,
  CAST(JSON_VALUE(base.metrics, '$.clicks') AS INT64) AS clicks,
  CAST(JSON_VALUE(base.metrics, '$.ctr') AS FLOAT64) AS ctr,
  p.app_install AS tiktok_app_install,
  p.purchase AS tiktok_purchase,
  p.conversion AS tiktok_conversion,
  p.start_trial AS tiktok_start_trial
FROM
  `${dataform.projectConfig.vars.rockadsProject}.tiktok_airbyte._7548374257156522001_ads_audience_reports_by_country_daily` base
LEFT JOIN
  `${dataform.projectConfig.vars.rockadsProject}.tiktok_airbyte._7548374257156522001_ads` ads
ON
  base.ad_id = ads.ad_id
LEFT JOIN
  `${dataform.projectConfig.vars.rockadsProject}.tiktok_airbyte._7548374257156522001_creative_assets_videos` assets
ON
  ads.video_id = assets.video_id
LEFT JOIN
  `${dataform.projectConfig.vars.rockadsProject}.tiktok.tiktok_purchase_*` p
ON
  DATE(base.stat_time_day) = p.stat_time_day
  AND CAST(base.ad_id AS STRING) = CAST(p.ad_id AS STRING)
  AND base.country_code = p.country_code
  AND CAST(p.advertiser_id AS STRING) = "7548374257156522001"
