config {
  type: "table",
  bigquery: {
    partitionBy: "ad_insight_date_start",
    clusterBy: ["country"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "ads_insights_by_country_merged",
  dependencies: ["ads_insights_by_country_all", "ads_insights_by_country_action_values_all", "ads_insights_by_country_actions_all", "ads_insights_by_country_conversions_all"],
  schema: "fb_airbyte_datamarts",
  tags: ['facebook_airbyte_all']
}

SELECT t1.* , t2.action_value_total_purchase, t2.action_value_total_onsite_web_app_purchase, t2.action_value_total_web_in_store_purchase, t2.action_value_total_omni_purchase, t2.action_value_total_fb_pixel_purchase, t2.action_value_total_onsite_web_purchase, t2.action_value_total_fb_mobile_purchase,
t3.action_count_post_engagement, t3.action_count_page_engagement, t3.action_count_link_click, t3.action_count_post_reaction, t3.action_count_landing_page_view, t3.action_count_purchase, t3.action_count_web_in_store_purchaset, t3.action_count_omni_add_to_cart, t3.action_count_add_to_cart, t3.action_count_onsite_web_app_add_to_cart, t3.action_count_onsite_web_add_to_cart, t3.action_count_onsite_web_purchase, t3.action_count_onsite_web_app_purchase, t3.action_count_fb_pixel_add_to_cart, t3.action_count_fb_pixel_purchase, t3.action_count_omni_purchase,t3.action_count_omni_app_install,t3.action_count_mobile_app_install,t3.action_count_app_install,t3.action_count_fb_mobile_purchase,t3.action_count_fb_video_view,
t4.conversion_subscribe_website_value, t4.conversion_subscribe_mobile_app, t4.conversion_subscribe_total, t4.conversion_values_subscribe_website_value, t4.conversion_values_subscribe_mobile_app, t4.conversion_values_subscribe_total,
t5.thumbnail_url, t5.video_url
FROM `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte_datamarts.ads_insights_by_country_all` t1
LEFT JOIN
    `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte_datamarts.ads_insights_by_country_action_values_all` AS t2
    ON t1.ad_id = t2.ad_id
    AND t1.ad_insight_date_start = t2.ad_insight_date_start
    AND t1.country = t2.country
    AND t1.objective = t2.objective
    AND t1.account_id = t2.account_id
LEFT JOIN
    `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte_datamarts.ads_insights_by_country_actions_all` AS t3
    ON t1.ad_id = t3.ad_id
    AND t1.ad_insight_date_start = t3.ad_insight_date_start
    AND t1.country = t3.country
    AND t1.objective = t3.objective
    AND t1.account_id = t3.account_id
LEFT JOIN
    `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte_datamarts.ads_insights_by_country_conversions_all` AS t4
    ON t1.ad_id = t4.ad_id
    AND t1.ad_insight_date_start = t4.ad_insight_date_start
    AND t1.country = t4.country
    AND t1.objective = t4.objective
    AND t1.account_id = t4.account_id
LEFT JOIN
    `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte_datamarts.creatives_773901696065588` AS t5
    ON t1.ad_id = t5.ad_id
