config {
  type: "table",
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id1662905686_facebook_links_urls",
  schema: "id1662905686_appsflyer_ds",
  dependencies: ['id1662905686_platforms_merged_metrics_all_cost_geo_unique'],
  tags: ['appsflyer_id1662905686_main']
}
SELECT * EXCEPT(report_date) FROM (
SELECT
DISTINCT
    ad_name AS ad,
    ad_insight_date_start AS report_date,
    'id1662905686' AS app_id,
    'Facebook Ads' as media_source,
    cast(null as string) as appsflyer_os_id,
    thumbnail_url,
    video_url,
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte_datamarts.ads_insights_by_country_merged_1186788694772131`
  WHERE
    account_id in ('1280504555400544', '1280509545400045')

  GROUP BY
    ALL
) QUALIFY row_number() over(partition by ad ORDER BY report_date desc) = 1
