config {
  type: "table",
    bigquery: {
    partitionBy: "event_date",
    clusterBy: ["country_code"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6738990592_organic_activity_revenues",
  schema: "id6738990592_appsflyer_ds",
  tags: ['appsflyer_id6738990592_main']
}
WITH bounds AS (
  SELECT
    -- realtime start
    TIMESTAMP(
      DATETIME(
        CASE
          WHEN EXTRACT(HOUR FROM CURRENT_DATETIME('UTC')) < 4
            THEN DATE_SUB(CURRENT_DATE('UTC'), INTERVAL 1 DAY)
          ELSE CURRENT_DATE('UTC')
        END,
        TIME '00:00:00'
      ),
      'UTC'
    ) AS realtime_start_ts,

    -- realtime end
    TIMESTAMP(
      DATETIME(
        CASE
          WHEN EXTRACT(HOUR FROM CURRENT_DATETIME('UTC')) < 4
            THEN CURRENT_DATE('UTC')
          ELSE DATE_ADD(CURRENT_DATE('UTC'), INTERVAL 1 DAY)
        END,
        CASE
          WHEN EXTRACT(HOUR FROM CURRENT_DATETIME('UTC')) < 4
            THEN TIME '04:00:00'
          ELSE TIME '00:00:00'
        END
      ),
      'UTC'
    ) AS realtime_end_ts
),
  main_raw_data AS (
  # IOS
  SELECT
    'ORGANIC' as campaign,
    'ORGANIC' as af_adset,
    'ORGANIC' as af_ad,
    'ORGANIC' as af_ad_id,
    'ORGANIC' as media_source,
    'id6738990592' as appsflyer_os_id,
    country_code,
    DATE(event_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.appsflyer.id6738990592_organic_in_app_events`
  WHERE event_time < (SELECT realtime_start_ts FROM bounds)

  UNION ALL
    SELECT
    'ORGANIC' as campaign,
    'ORGANIC' as af_adset,
    'ORGANIC' as af_ad,
    'ORGANIC' as af_ad_id,
    'ORGANIC' as media_source,
    'id6738990592' as appsflyer_os_id,
    country_code,
    DATE(event_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
    FROM
        `rockads-thirdparty.realtime_appsflyer_events.id6738990592_events_latest`
    WHERE
        event_time >= (SELECT realtime_start_ts FROM bounds)
        AND event_time <  (SELECT realtime_end_ts   FROM bounds)
        AND media_source = 'organic'

  # Android
  UNION ALL
     SELECT
        'ORGANIC' as campaign,
        'ORGANIC' as af_adset,
        'ORGANIC' as af_ad,
        'ORGANIC' as af_ad_id,
        'ORGANIC' as media_source,
        'com_videoai_effects' as appsflyer_os_id,
        country_code,
        DATE(event_time) AS event_date,
        CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
        CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
        CAST(event_revenue AS FLOAT64) event_revenue
      FROM
        `${dataform.projectConfig.vars.rockadsProject}.appsflyer.com_videoai_effects_organic_in_app_events`
    WHERE event_time < (SELECT realtime_start_ts FROM bounds)

    UNION ALL
     SELECT
        'ORGANIC' as campaign,
        'ORGANIC' as af_adset,
        'ORGANIC' as af_ad,
        'ORGANIC' as af_ad_id,
        'ORGANIC' as media_source,
        'com_videoai_effects' as appsflyer_os_id,
        country_code,
        DATE(event_time) AS event_date,
        CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
        CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
        CAST(event_revenue AS FLOAT64) event_revenue
    FROM
      `rockads-thirdparty.realtime_appsflyer_events.com_videoai_effects_events_latest`
    WHERE
        event_time >= (SELECT realtime_start_ts FROM bounds)
        AND event_time <  (SELECT realtime_end_ts   FROM bounds)
        AND media_source = 'organic'
    )
SELECT
  *
FROM (
  SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    country_code,
    media_source,
    appsflyer_os_id,
    event_date,
    SUM(
    IF
      (event_value_af_revenue=0,0,event_value_af_price)) AS activity_event_value_af_price,
    SUM(event_value_af_revenue) AS activity_event_value_af_revenue,
    SUM(CAST(event_revenue AS FLOAT64)) activity_event_revenue
  FROM
    main_raw_data
  GROUP BY
    ALL )