config {
  type: "table",
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id1363478842_tiktok_links_urls",
  schema: "id1363478842_appsflyer_ds",
  dependencies: ['id1363478842_facebook_links_urls'],
  tags: ['appsflyer_id1363478842_main']
}
SELECT * EXCEPT(report_date) FROM (
SELECT
DISTINCT
    ad_name AS ad,
    stat_time_day AS report_date,
    'id1363478842' AS app_id,
    'tiktokglobal_int' as media_source,
    cast(null as string) as appsflyer_os_id,
    video_thumbnail_url as thumbnail_url,
    video_url,
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.tiktok_airbyte_datamarts.ads_audience_reports_by_country_merged_id1363478842`
  GROUP BY
    ALL
) QUALIFY row_number() over(partition by ad ORDER BY report_date desc) = 1
