config {
  type: "table",
  bigquery: {
    partitionBy: "ad_insight_date_start",
    clusterBy: ["country"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "ads_insights_by_country_7311415715539931_fabula",
  schema: "fb_airbyte_datamarts",
  tags: ['facebook_airbyte_7311415715539931_fabula']
}

WITH clean_campaigns AS (
  SELECT
    id AS campaign_id,
    name AS campaign_name,
    objective,
    start_time,
    stop_time
  FROM `rockads-thirdparty.fb_airbyte._7311415715539931_fabula_campaigns`
),

clean_ad_sets AS (
  SELECT
    id AS adset_id,
    start_time,
    end_time,
    name AS adset_name,
    campaign_id,
    effective_status,
    bid_strategy,
    daily_budget,
    bid_amount
  FROM `rockads-thirdparty.fb_airbyte._7311415715539931_fabula_ad_sets`
),

clean_ads AS (
  SELECT
    id AS ad_id,
    campaign_id,
    adset_id,
    status,
    last_updated_by_app_id,
    name AS ad_name,
    created_time
  FROM `rockads-thirdparty.fb_airbyte._7311415715539931_fabula_ads`
),

clean_ads_insights AS (
  SELECT
    ad_id,
    account_id,
    account_name,
    country,
    objective,
    account_currency,
    NULL as created_time,
    date_start,
    spend AS insights_spend,
    impressions AS insights_impressions,
    clicks AS insights_clicks,
    ctr AS insights_ctr,
    cpc AS insights_cpc,
    cpm AS insights_cpm,
    cpp AS insights_cpp,
    unique_clicks,
    conversions,
    cost_per_conversion,
    purchase_roas,
    website_purchase_roas,
    outbound_clicks,
    inline_post_engagement,
    cost_per_action_type,
    action_values,
    video_play_actions,
        (
      SELECT SUM(CAST(JSON_VALUE(click, '$.value') AS INT64))
      FROM UNNEST(JSON_EXTRACT_ARRAY(outbound_clicks)) AS click
      WHERE JSON_VALUE(click, '$.value') IS NOT NULL
    ) AS total_outbound_clicks
  FROM `rockads-thirdparty.facebook_marketing.fabula_1186788694772131_*`
  --WHERE spend > 0 -- Filter out insights data with no spend
)

SELECT
  i.ad_id,
  i.created_time as ad_insight_created_time,
  i.date_start as ad_insight_date_start,
  i.account_id,
  i.account_name,
  i.account_currency,
  i.country,
  i.objective,
  a.ad_name,
  a.last_updated_by_app_id,
  a.status as ad_status,
  sa.adset_name,
  sa.effective_status as adset_effective_status,
  sa.bid_strategy as adset_bid_strategy,
  sa.daily_budget as adset_daily_budget,
  sa.start_time as adset_start_time,
  sa.end_time as adset_end_time,
  ca.campaign_id,
  ca.campaign_name,
  ca.start_time as campaign_start_time,
  ca.stop_time as campaign_stop_time,
  COALESCE(i.insights_spend, 0) AS total_spend,
  COALESCE(i.insights_impressions, 0) AS total_impressions,
  COALESCE(i.insights_clicks, 0) AS total_clicks,
  COALESCE(i.insights_ctr, 0) AS ctr,
  COALESCE(i.insights_cpc, 0) AS cpc,
  COALESCE(i.insights_cpm, 0) AS cpm,
  COALESCE(i.insights_cpp, 0) AS cpp,
  COALESCE(i.unique_clicks, 0) AS unique_clicks,
  COALESCE(i.inline_post_engagement, 0) AS inline_post_engagement
FROM clean_ads_insights i
LEFT JOIN clean_ads a ON i.ad_id = a.ad_id
LEFT JOIN clean_campaigns ca ON a.campaign_id = ca.campaign_id
LEFT JOIN clean_ad_sets sa ON a.adset_id = sa.adset_id