config {
  type: "table",
  bigquery: {
    partitionBy: "ad_insight_date_start",
    clusterBy: ["country"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "ads_insights_by_country_action_values_7311415715539931_fabula",
  schema: "fb_airbyte_datamarts",
  tags: ['facebook_airbyte_7311415715539931_fabula']
}

WITH main_data as (
SELECT
  NULL as ad_insight_created_time,
  date_start,
  account_id,
  account_name,
  account_currency,
  ad_id,
  ad_name,
  country,
  campaign_name,
  campaign_id,
  objective,
JSON_EXTRACT_ARRAY(action_values) AS json_array_action_values,

 FROM `${dataform.projectConfig.vars.rockadsProject}.facebook_marketing.fabula_1186788694772131_*`
),
clean_ads AS (
  SELECT
    id,
    campaign_id,
    adset_id,
    last_updated_by_app_id,
    status as ad_status,
    name AS ad_name,
    created_time
  FROM `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte._7311415715539931_fabula_ads`
),
clean_campaigns AS (
  SELECT
    id AS campaign_id,
    name AS campaign_name,
    objective,
    start_time,
    stop_time
  FROM `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte._7311415715539931_fabula_campaigns`
),

clean_ad_sets AS (
  SELECT
    id AS adset_id,
    start_time,
    end_time,
    name AS adset_name,
    campaign_id,
    effective_status,
    bid_strategy,
    daily_budget,
    bid_amount
  FROM `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte._7311415715539931_fabula_ad_sets`
)

SELECT
  ad_id,
  ad_insight_created_time,
  ad_insight_date_start,
  account_id,
  account_name,
  account_currency,
  country,
  objective,
  ad_name,
  last_updated_by_app_id,
  ad_status,
  adset_name,
  adset_effective_status,
  adset_bid_strategy,
  adset_daily_budget,
  adset_start_time,
  adset_end_time,
  campaign_id,
  campaign_name,
  campaign_start_time,
  campaign_stop_time,
SUM(CAST(purchase AS FLOAT64)) as action_value_total_purchase,
SUM(CAST(onsite_web_app_purchase AS FLOAT64)) as action_value_total_onsite_web_app_purchase,
SUM(CAST(web_in_store_purchase AS FLOAT64)) as action_value_total_web_in_store_purchase,
SUM(CAST(omni_purchase AS FLOAT64)) as action_value_total_omni_purchase,
SUM(CAST(fb_pixel_purchase AS FLOAT64)) as action_value_total_fb_pixel_purchase,
SUM(CAST(onsite_web_purchase AS FLOAT64)) as action_value_total_onsite_web_purchase,
SUM(CAST(fb_mobile_purchase AS FLOAT64)) as action_value_total_fb_mobile_purchase,
SUM(CAST(complete_registration AS FLOAT64)) as action_value_total_complete_registration,
SUM(CAST(omni_complete_registration AS FLOAT64)) as action_value_total_omni_complete_registration,
SUM(CAST(omni_initiated_checkout AS FLOAT64)) as action_value_total_omni_initiated_checkout,
SUM(CAST(initiate_checkout AS FLOAT64)) as action_value_total_initiate_checkout,
SUM(CAST(omni_landing_page_view AS FLOAT64)) as action_value_total_omni_landing_page_view,
SUM(CAST(fb_pixel_add_payment_info AS FLOAT64)) as action_value_total_fb_pixel_add_payment_info,
SUM(CAST(fb_pixel_complete_registration AS FLOAT64)) as action_value_total_fb_pixel_complete_registration,
SUM(CAST(fb_pixel_initiate_checkout AS FLOAT64)) as action_value_total_fb_pixel_initiate_checkout,
SUM(CAST(fb_pixel_lead AS FLOAT64)) as action_value_total_fb_pixel_lead,
SUM(CAST(add_payment_info AS FLOAT64)) as action_value_total_add_payment_info,
SUM(CAST(web_app_in_store_purchase AS FLOAT64)) as action_value_total_web_app_in_store_purchase,
SUM(CAST(messaging_conversation_started_7d AS FLOAT64)) as action_value_total_messaging_conversation_started_7d,
FROM (
select
  i.ad_id,
  i.ad_insight_created_time,
  i.date_start as ad_insight_date_start,
  i.account_id,
  i.account_name,
  i.account_currency,
  i.country,
  i.objective,
  cds.ad_name,
  cds.last_updated_by_app_id,
  cds.ad_status,
  sa.adset_name,
  sa.effective_status as adset_effective_status,
  sa.bid_strategy as adset_bid_strategy,
  sa.daily_budget as adset_daily_budget,
  sa.start_time as adset_start_time,
  sa.end_time as adset_end_time,
  ca.campaign_id,
  ca.campaign_name,
  ca.start_time as campaign_start_time,
  ca.stop_time as campaign_stop_time,
CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'purchase' THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS purchase,
CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'onsite_web_app_purchase' THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS onsite_web_app_purchase,
CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'web_in_store_purchase' THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS web_in_store_purchase,
CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'omni_purchase' THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS omni_purchase,
CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'offsite_conversion.fb_pixel_purchase' THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS fb_pixel_purchase,
CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'onsite_web_purchase' THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS onsite_web_purchase,
CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'app_custom_event.fb_mobile_purchase' THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS fb_mobile_purchase,
CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'complete_registration'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS complete_registration,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'omni_complete_registration'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS omni_complete_registration,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'omni_initiated_checkout'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS omni_initiated_checkout,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'initiate_checkout'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS initiate_checkout,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'omni_landing_page_view'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS omni_landing_page_view,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'offsite_conversion.fb_pixel_add_payment_info'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS fb_pixel_add_payment_info,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'offsite_conversion.fb_pixel_complete_registration'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS fb_pixel_complete_registration,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'offsite_conversion.fb_pixel_initiate_checkout'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS fb_pixel_initiate_checkout,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'offsite_conversion.fb_pixel_lead'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS fb_pixel_lead,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'add_payment_info'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS add_payment_info,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'web_app_in_store_purchase'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS web_app_in_store_purchase,

CASE WHEN JSON_EXTRACT_SCALAR(action_values_element, '$.action_type') = 'onsite_conversion.messaging_conversation_started_7d'
     THEN JSON_EXTRACT_SCALAR(action_values_element, '$.value') ELSE NULL END AS messaging_conversation_started_7d,
from main_data  i , UNNEST(json_array_action_values) as action_values_element
LEFT JOIN clean_ads cds ON i.ad_id = cds.id
LEFT JOIN clean_campaigns ca ON cds.campaign_id = ca.campaign_id
LEFT JOIN clean_ad_sets sa ON cds.adset_id = sa.adset_id
)GROUP BY ALL