config {
  type: "table",
  bigquery: {
    partitionBy: "ad_insight_date_start",
    clusterBy: ["country"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "ads_insights_by_country_merged_7311415715539931_fabula",
  dependencies: ["ads_insights_by_country_7311415715539931_fabula", "ads_insights_by_country_action_values_7311415715539931_fabula", "ads_insights_by_country_actions_7311415715539931_fabula", "ads_insights_by_country_conversions_7311415715539931_fabula"],
  schema: "fb_airbyte_datamarts",
  tags: ['facebook_airbyte_7311415715539931_fabula']
}

SELECT
  t1.*,
  t2.action_value_total_purchase,
  t2.action_value_total_onsite_web_app_purchase,
  t2.action_value_total_web_in_store_purchase,
  t2.action_value_total_omni_purchase,
  t2.action_value_total_fb_pixel_purchase,
  t2.action_value_total_onsite_web_purchase,
  t2.action_value_total_fb_mobile_purchase,
  t2.action_value_total_complete_registration,
  t2.action_value_total_omni_complete_registration,
  t2.action_value_total_omni_initiated_checkout,
  t2.action_value_total_initiate_checkout,
  t2.action_value_total_omni_landing_page_view,
  t2.action_value_total_fb_pixel_add_payment_info,
  t2.action_value_total_fb_pixel_complete_registration,
  t2.action_value_total_fb_pixel_initiate_checkout,
  t2.action_value_total_fb_pixel_lead,
  t2.action_value_total_add_payment_info,
  t2.action_value_total_web_app_in_store_purchase,
  t2.action_value_total_messaging_conversation_started_7d,
  t3.action_count_post_engagement,
  t3.action_count_page_engagement,
  t3.action_count_link_click,
  t3.action_count_post_reaction,
  t3.action_count_landing_page_view,
  t3.action_count_purchase,
  t3.action_count_web_in_store_purchase,
  t3.action_count_omni_add_to_cart,
  t3.action_count_add_to_cart,
  t3.action_count_onsite_web_app_add_to_cart,
  t3.action_count_onsite_web_add_to_cart,
  t3.action_count_onsite_web_purchase,
  t3.action_count_onsite_web_app_purchase,
  t3.action_count_fb_pixel_add_to_cart,
  t3.action_count_fb_pixel_purchase,
  t3.action_count_omni_purchase,
  t3.action_count_omni_app_install,
  t3.action_count_mobile_app_install,
  t3.action_count_app_install,
  t3.action_count_fb_mobile_purchase,
  t3.action_count_complete_registration,
  t3.action_count_omni_complete_registration,
  t3.action_count_omni_initiated_checkout,
  t3.action_count_initiate_checkout,
  t3.action_count_omni_landing_page_view,
  t3.action_count_fb_pixel_add_payment_info,
  t3.action_count_fb_pixel_complete_registration,
  t3.action_count_fb_pixel_initiate_checkout,
  t3.action_count_fb_pixel_lead,
  t3.action_count_add_payment_info,
  t3.action_count_web_app_in_store_purchase,
  t3.action_count_messaging_conversation_started_7d,
  t4.conversion_subscribe_website_value,
  t4.conversion_subscribe_mobile_app,
  t4.conversion_subscribe_total,
  t5.thumbnail_url,
  t5.video_url
FROM
  `rockads-thirdparty.fb_airbyte_datamarts.ads_insights_by_country_7311415715539931_fabula` t1
LEFT JOIN
  `rockads-thirdparty.fb_airbyte_datamarts.ads_insights_by_country_action_values_7311415715539931_fabula` AS t2
ON
  t1.ad_id = t2.ad_id
  AND t1.ad_insight_date_start = t2.ad_insight_date_start
  AND t1.country = t2.country
  AND t1.objective = t2.objective
  AND t1.account_id = t2.account_id
LEFT JOIN
  `rockads-thirdparty.fb_airbyte_datamarts.ads_insights_by_country_actions_7311415715539931_fabula` AS t3
ON
  t1.ad_id = t3.ad_id
  AND t1.ad_insight_date_start = t3.ad_insight_date_start
  AND t1.country = t3.country
  AND t1.objective = t3.objective
  AND t1.account_id = t3.account_id
LEFT JOIN
  `rockads-thirdparty.fb_airbyte_datamarts.ads_insights_by_country_conversions_7311415715539931_fabula` AS t4
ON
  t1.ad_id = t4.ad_id
  AND t1.ad_insight_date_start = t4.ad_insight_date_start
  AND t1.country = t4.country
  AND t1.objective = t4.objective
  AND t1.account_id = t4.account_id
LEFT JOIN
  `rockads-thirdparty.fb_airbyte_datamarts.creatives_7311415715539931_fabula` AS t5
ON
  t1.ad_id = t5.ad_id