config {
  type: "table",
    bigquery: {
    partitionBy: "install_date",
    clusterBy: ["country_code"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6443832829_revenue_ltv",
  schema: "id6443832829_appsflyer_ds",
  dependencies: ['id6443832829_revenues'],
  tags: ['appsflyer_id6443832829_main']
}

WITH main_data as (
SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'id6443832829' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    DATE(event_time) as event_time,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.appsflyer.id6443832829_in_app_events`
    where app_id in ('id6443832829', 'com.inspire.ai') AND DATE(event_time) < '2025-06-16'

  UNION ALL
   SELECT
    IF(campaign='',NULL, campaign) AS campaign,
    IF(af_adset='',NULL, af_adset) AS af_adset,
    IF(af_ad ='',NULL, af_ad) AS af_ad,
    IF(af_ad_id='',NULL, af_ad_id) AS af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE IF(media_source='',NULL, media_source) end as media_source,
    'id6443832829' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    DATE(event_time) as event_time,
    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_price'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_price,

    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_revenue'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_revenue,
    SAFE_CAST(NULLIF(event_revenue, '') AS FLOAT64) AS event_revenue
  FROM
    `rockads-thirdparty.appsflyer_airflow.id6443832829_in_app_events`
    where DATE(event_time) >= '2025-06-16' AND event_time < '${realtime_marketing.realtime_start_ts_calc}'
    
    UNION ALL
    SELECT
        campaign,
        adset,
        af_ad,
        af_ad_id,
        CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
        'id6443832829' as appsflyer_os_id,
        country_code,
        DATE(install_time) AS event_date,
        DATE(event_time) as event_time,
        CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
        CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
        CAST(event_revenue AS FLOAT64) event_revenue
      FROM
        `rockads-thirdparty.realtime_appsflyer_events.id6443832829_events_latest`
        WHERE
        event_time >= '${realtime_marketing.realtime_start_ts_calc}'
        AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
        AND media_source != 'organic'

UNION ALL
 SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'com_inspire_ai' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    DATE(event_time) as event_time,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.appsflyer.com_inspire_ai_in_app_events`
    where app_id in ('id6443832829', 'com.inspire.ai') and event_time < '${realtime_marketing.realtime_start_ts_calc}'
    UNION ALL
    
 SELECT
    campaign,
    adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'com_inspire_ai' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    DATE(event_time) as event_time,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `rockads-thirdparty.realtime_appsflyer_events.com_inspire_ai_events_latest`
    WHERE
        event_time >= '${realtime_marketing.realtime_start_ts_calc}'
        AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
        AND media_source != 'organic'

  UNION ALL
  SELECT
    'ORGANIC' as campaign,
    'ORGANIC' as af_adset,
    'ORGANIC' as af_ad,
    'ORGANIC' as af_ad_id,
    'ORGANIC' as media_source,
    'id6443832829' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    DATE(event_time) as event_time,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.appsflyer.id6443832829_organic_in_app_events`
   WHERE event_time < '${realtime_marketing.realtime_start_ts_calc}'
  UNION ALL
  SELECT
    'ORGANIC' as campaign,
    'ORGANIC' as af_adset,
    'ORGANIC' as af_ad,
    'ORGANIC' as af_ad_id,
    'ORGANIC' as media_source,
    'id6443832829' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    DATE(event_time) as event_time,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `rockads-thirdparty.realtime_appsflyer_events.id6443832829_events_latest`
    WHERE
        event_time >= '${realtime_marketing.realtime_start_ts_calc}'
        AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
        AND media_source = 'organic'
        
  UNION ALL
     SELECT
        'ORGANIC' as campaign,
        'ORGANIC' as af_adset,
        'ORGANIC' as af_ad,
        'ORGANIC' as af_ad_id,
        'ORGANIC' as media_source,
        'com_inspire_ai' as appsflyer_os_id,
        country_code,
        DATE(install_time) AS event_date,
        DATE(event_time) as event_time,
        CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
        CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
        CAST(event_revenue AS FLOAT64) event_revenue
      FROM
        `${dataform.projectConfig.vars.rockadsProject}.appsflyer.com_inspire_ai_organic_in_app_events`
       WHERE event_time < '${realtime_marketing.realtime_start_ts_calc}'
   UNION ALL
    SELECT
      'ORGANIC' as campaign,
      'ORGANIC' as af_adset,
      'ORGANIC' as af_ad,
      'ORGANIC' as af_ad_id,
      'ORGANIC' as media_source,
      'com_inspire_ai' as appsflyer_os_id,
      country_code,
      DATE(install_time) AS event_date,
      DATE(event_time) as event_time,
      CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
      CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
      CAST(event_revenue AS FLOAT64) event_revenue
    FROM
      `rockads-thirdparty.realtime_appsflyer_events.com_inspire_ai_events_latest`
    WHERE
        event_time >= '${realtime_marketing.realtime_start_ts_calc}'
        AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
        AND media_source = 'organic'
),

revenue_with_days AS (
  SELECT
    campaign,
    af_ad,
    af_adset,
    media_source,
    appsflyer_os_id,
    country_code,
    event_date AS install_date,
    event_time,
    DATE_DIFF(event_time, event_date, DAY) AS day_number,
    event_revenue
  FROM main_data
  WHERE event_revenue IS NOT NULL
),

daily_revenue AS (
  SELECT
    install_date,
    campaign,
    af_ad,
    af_adset,
    media_source,
    appsflyer_os_id,
    country_code,
    day_number,
    SUM(event_revenue) AS revenue
  FROM revenue_with_days
  WHERE day_number >= 0
  GROUP BY
    install_date, campaign, af_ad, af_adset, media_source, appsflyer_os_id, country_code, day_number
),

cumulative_revenue AS (
  SELECT
    install_date,
    campaign,
    af_ad,
    af_adset,
    media_source,
    appsflyer_os_id,
    country_code,

    CASE
      WHEN install_date <= CURRENT_DATE() THEN SUM(CASE
        WHEN day_number = 0 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d0_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 1 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 1 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d1_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 3 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 3 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d3_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 7 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 7 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d7_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 15 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 15 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d15_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 30 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 30 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d30_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 60 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 60 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d60_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 90 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 90 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d90_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 120 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 120 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d120_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 150 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 150 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d150_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 180 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 180 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d180_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 210 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 210 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d210_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 240 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 240 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d240_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 270 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 270 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d270_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 300 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 300 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d300_revenue,
    
    CASE
      WHEN DATE_ADD(install_date, INTERVAL 330 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 330 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d330_revenue,

    CASE
      WHEN DATE_ADD(install_date, INTERVAL 360 DAY) <= CURRENT_DATE() THEN
        SUM(CASE WHEN day_number <= 360 THEN revenue ELSE 0 END)
      ELSE NULL
    END AS d360_revenue,

    SUM(revenue) AS ltv_revenue

  FROM daily_revenue
  GROUP BY
    install_date, campaign, af_ad, af_adset, media_source, appsflyer_os_id, country_code
)

SELECT
  install_date,
  campaign,
  IFNULL(af_ad, 'None') as af_ad,
  IFNULL(af_adset, 'None') as af_adset,
  media_source,
  appsflyer_os_id,
  country_code,
  ROUND(d0_revenue, 2) AS d0,
  ROUND(d1_revenue, 2) AS d1,
  ROUND(d3_revenue, 2) AS d3,
  ROUND(d7_revenue, 2) AS d7,
  ROUND(d15_revenue, 2) AS d15,
  ROUND(d30_revenue, 2) AS d30,
  ROUND(d60_revenue, 2) AS d60,
  ROUND(d90_revenue, 2) AS d90,
  ROUND(d120_revenue, 2) AS d120,
  ROUND(d150_revenue, 2) AS d150,
  ROUND(d180_revenue, 2) AS d180,
  ROUND(d210_revenue, 2) AS d210,
  ROUND(d240_revenue, 2) AS d240,
  ROUND(d270_revenue, 2) AS d270,
  ROUND(d300_revenue, 2) AS d300,
  ROUND(d330_revenue, 2) AS d330,
  ROUND(d360_revenue, 2) AS d360,
  ROUND(ltv_revenue, 2) AS ltv
FROM cumulative_revenue
