config {
  type: "table",
    bigquery: {
    partitionBy: "event_date",
    clusterBy: ["country_code"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6738990592_revenues",
  schema: "id6738990592_appsflyer_ds",
  dependencies: ['id6738990592_platforms_merged_all_cost_geo'],
  tags: ['appsflyer_id6738990592_main']
}

WITH bounds AS (
  SELECT
    -- realtime start
    TIMESTAMP(
      DATETIME(
        CASE
          WHEN EXTRACT(HOUR FROM CURRENT_DATETIME('UTC')) < 4
            THEN DATE_SUB(CURRENT_DATE('UTC'), INTERVAL 1 DAY)
          ELSE CURRENT_DATE('UTC')
        END,
        TIME '00:00:00'
      ),
      'UTC'
    ) AS realtime_start_ts,

    -- realtime end
    TIMESTAMP(
      DATETIME(
        CASE
          WHEN EXTRACT(HOUR FROM CURRENT_DATETIME('UTC')) < 4
            THEN CURRENT_DATE('UTC')
          ELSE DATE_ADD(CURRENT_DATE('UTC'), INTERVAL 1 DAY)
        END,
        CASE
          WHEN EXTRACT(HOUR FROM CURRENT_DATETIME('UTC')) < 4
            THEN TIME '04:00:00'
          ELSE TIME '00:00:00'
        END
      ),
      'UTC'
    ) AS realtime_end_ts
),
main_raw_data AS (
  SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'id6738990592' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `rockads-thirdparty.appsflyer.id6738990592_in_app_events`
    where app_id in ('id6738990592', 'com.videoai.effects') AND DATE(event_time) < '2025-06-01'

  UNION ALL
   SELECT
    IF(campaign='',NULL, campaign) AS campaign,
    IF(af_adset='',NULL, af_adset) AS af_adset,
    IF(af_ad ='',NULL, af_ad) AS af_ad,
    IF(af_ad_id='',NULL, af_ad_id) AS af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE IF(media_source='',NULL, media_source) end as media_source,
    'id6738990592' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_price'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_price,

    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_revenue'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_revenue,
    SAFE_CAST(NULLIF(event_revenue, '') AS FLOAT64) AS event_revenue
  FROM
    `rockads-thirdparty.appsflyer_airflow.id6738990592_in_app_events`
    where DATE(event_time) >= '2025-06-01' AND event_time < (SELECT realtime_start_ts FROM bounds)

  UNION ALL
    SELECT
    campaign,
    adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'id6738990592' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `rockads-thirdparty.realtime_appsflyer_events.id6738990592_events_latest`
  WHERE
  event_time >= (SELECT realtime_start_ts FROM bounds)
  AND event_time <  (SELECT realtime_end_ts   FROM bounds)
  AND media_source != 'organic'

 UNION ALL
 SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'com_videoai_effects' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `rockads-thirdparty.appsflyer.com_videoai_effects_in_app_events`
    where app_id in ('id6738990592', 'com.videoai.effects') AND DATE(event_time) < '2025-06-12'
UNION ALL
   SELECT
    IF(campaign='',NULL, campaign) AS campaign,
    IF(af_adset='',NULL, af_adset) AS af_adset,
    IF(af_ad ='',NULL, af_ad) AS af_ad,
    IF(af_ad_id='',NULL, af_ad_id) AS af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE IF(media_source='',NULL, media_source) end as media_source,
    'com_videoai_effects' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_price'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_price,

    SAFE_CAST(
      REGEXP_REPLACE(
        JSON_EXTRACT_SCALAR(event_value, '$.af_revenue'),
        r'[^0-9\.]',  -- remove all non-numeric characters except the period
        ''
      ) AS FLOAT64
    ) AS event_value_af_revenue,
    SAFE_CAST(NULLIF(event_revenue, '') AS FLOAT64) AS event_revenue
  FROM
    `rockads-thirdparty.appsflyer_airflow.com_videoai_effects_in_app_events`
    where DATE(event_time) >= '2025-06-12' AND event_time < (SELECT realtime_start_ts FROM bounds)


  UNION ALL
    SELECT
    campaign,
    adset,
    af_ad,
    af_ad_id,
    CASE WHEN media_source in ('facebook','restricted') then 'Facebook Ads' ELSE media_source end as media_source,
    'com_videoai_effects' as appsflyer_os_id,
    country_code,
    DATE(install_time) AS event_date,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_price')AS FLOAT64) AS event_value_af_price,
    CAST(JSON_EXTRACT_SCALAR(event_value, '$.af_revenue')AS FLOAT64) AS event_value_af_revenue,
    CAST(event_revenue AS FLOAT64) event_revenue
  FROM
    `rockads-thirdparty.realtime_appsflyer_events.com_videoai_effects_events_latest`
  WHERE
  event_time >= (SELECT realtime_start_ts FROM bounds)
  AND event_time <  (SELECT realtime_end_ts   FROM bounds)
  AND media_source != 'organic'


    )
SELECT
  *
FROM (
  SELECT
    campaign,
    af_adset,
    af_ad,
    af_ad_id,
    country_code,
    media_source,
    appsflyer_os_id,
    event_date,
    SUM(
    IF
      (event_value_af_revenue=0,0,event_value_af_price)) AS event_value_af_price,
    SUM(event_value_af_revenue) AS event_value_af_revenue,
    SUM(CAST(event_revenue AS FLOAT64)) event_revenue
  FROM
    main_raw_data
  GROUP BY
    ALL )