config {
  type: "table",
  bigquery: {
    partitionBy: "report_date",
    clusterBy: ["country_code","app_name"]
   },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  schema: "id6473276045_appsflyer_ds",
  name: "esim_all_web_ads_purchase_refund_combined_zotlo",
  tags: ["id6473276045_zotlo"],
  dependencies: ['esim_all_users_original_event_dates'],
  description: "Combined daily purchase and refund data for Zotlo, with refunds as negative amounts."
}


SELECT
date AS report_date,
app_name,
UPPER(country) AS country_code,
IFNULL(utm_content, '') AS ad_name,
IFNULL(utm_medium, '') AS ad_group_name,
IFNULL(utm_source, '') AS media_source,
IFNULL(utm_campaign, '') AS campaign_name,
IFNULL(transaction_type, 'zotlo_unkown_event') as event_name,
SUM(total_amount_usd) AS amount,
SUM(event_count) AS event_count
from `rockads-thirdparty.id6473276045_appsflyer_ds.esim_all_purchase_count_daily`
WHERE status="success" AND LOWER(platform)  = 'web'
group by ALL

UNION ALL

SELECT
date AS report_date,
app_name,
UPPER(country) AS country_code,
IFNULL(utm_content, '') AS ad_name,
IFNULL(utm_medium, '') AS ad_group_name,
IFNULL(utm_source, '') AS media_source,
IFNULL(utm_campaign, '') AS campaign_name,
IFNULL(transaction_type, 'zotlo_unkown_event') as event_name,
-SUM(total_amount_usd) AS amount,
SUM(total_transaction_count) AS event_count
from `rockads-thirdparty.id6473276045_appsflyer_ds.esim_all_refund_count_daily`
WHERE status="success" AND LOWER(platform)  = 'web'
group by ALL