config {
  type: "table",
    bigquery: {
    partitionBy: "event_date",
    clusterBy: ["country_code"]
  },
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6738388891_event_counts_unique",
  schema: "id6738388891_appsflyer_ds",
  dependencies: ['id6738388891_revenue_ltv'],
  tags: ['appsflyer_id6738388891_main']
}

WITH main_raw_data AS (
SELECT  campaign, af_adset, af_ad, af_ad_id, event_name,IF(media_source = 'restricted', 'Facebook Ads', media_source) as media_source,
'id6738388891' as appsflyer_os_id,
country_code,customer_user_id,
event_revenue,
DATE(install_time) as event_date,
FROM `${dataform.projectConfig.vars.rockadsProject}.appsflyer_airbyte.ai_cleaner_in_app_events`
WHERE DATE(event_time) < '2025-10-13'

UNION ALL
SELECT  IF(campaign='',NULL, campaign) AS campaign, IF(af_adset='',NULL, af_adset) AS af_adset, IF(af_ad='',NULL, af_ad) AS af_ad, IF(af_ad_id='',NULL, af_ad_id) AS af_ad_id, event_name,
IF(media_source = 'restricted', 'Facebook Ads', IF(media_source='',NULL, media_source)) as media_source,
'id6738388891' as appsflyer_os_id,
country_code,customer_user_id,
SAFE_CAST(NULLIF(event_revenue, '') AS STRING) AS event_revenue,
DATE(install_time) as event_date,
FROM `rockads-thirdparty.appsflyer_airflow.id6738388891_in_app_events`
where DATE(event_time) >= '2025-10-13'  AND event_time < '${realtime_marketing.realtime_start_ts_calc}'

UNION ALL
SELECT
  IF(campaign = '', NULL, campaign) AS campaign,
  IF(adset    = '', NULL, adset)    AS af_adset,
  IF(af_ad    = '', NULL, af_ad)    AS af_ad,
  IF(af_ad_id = '', NULL, af_ad_id) AS af_ad_id,
  event_name,
  IF(media_source = 'restricted', 'Facebook Ads', IF(media_source = '', NULL, media_source)) AS media_source,
  'id6738388891' AS appsflyer_os_id,
  country_code,
  customer_user_id,
  SAFE_CAST(NULLIF(event_revenue, 0) AS STRING) AS event_revenue,
  DATE(install_time) AS event_date
FROM `rockads-thirdparty.realtime_appsflyer_events.id6738388891_events_latest`
WHERE
  event_time >= '${realtime_marketing.realtime_start_ts_calc}'
  AND event_time <  '${realtime_marketing.realtime_end_ts_calc}'
  AND media_source != 'organic'
  

)
SELECT * FROM (
SELECT campaign, af_adset, af_ad, af_ad_id, country_code,
media_source,appsflyer_os_id, event_name,
event_date,
count(event_name) AS event_count,
count(distinct customer_user_id) AS unique_event_count,
sum(CAST(event_revenue AS FLOAT64)) AS revenue,
FROM main_raw_data 
GROUP BY ALL
)
PIVOT (
  MAX(event_count) as event_count, 
  MAX(unique_event_count)  as unique_event_count,
  MAX(revenue)  as revenue FOR event_name IN (
    'paywallShowed',
    'paymentInit',
    'rc_renewal_event',
    'rc_trial_converted_event',
    'rc_expiration_event',
    'rc_cancellation_event',
    'rc_billing_issue_event',
    'rc_initial_purchase_event',
    'rc_product_change_event',
    'rc_trial_started_event',
    'rc_trial_cancelled_event',
    'WebToAppInstall',
    'rc_non_subscription_purchase_event'
  )
)