config {
  type: "table",
  database: `${dataform.projectConfig.vars.rockadsProject}`,
  name: "id6738388891_facebook_links_urls",
  schema: "id6738388891_appsflyer_ds",
  dependencies: ['id6738388891_platforms_merged_metrics_all_cost_geo_unique'],
  tags: ['appsflyer_id6738388891_main']
}
SELECT * EXCEPT(report_date) FROM (
SELECT
DISTINCT
    ad_name AS ad,
    ad_insight_date_start AS report_date,
    'id6738388891' AS app_id,
    'Facebook Ads' as media_source,
    cast(null as string) as appsflyer_os_id,
    thumbnail_url,
    video_url,
  FROM
    `${dataform.projectConfig.vars.rockadsProject}.fb_airbyte_datamarts.ads_insights_by_country_merged`
  WHERE
    account_id in ('1032750390180716', '1033750273414061')

  GROUP BY
    ALL
) QUALIFY row_number() over(partition by ad ORDER BY report_date desc) = 1
